### ISSUE TITLE
7zip/zip support + extra M3U features

### ISSUE THREAD

**Issue by veganvelociraptor** [libretro/libretro-cap32#103]
The VICE core has some added features to its m3u support described here: https://docs.libretro.com/library/vice/#extra-m3u-features

I'd like to request similar features being added to the Caprice32 core, which would make it possible to use m3u files like in this example: Alive (F).m3u

> Alive (F).7z#Alive (F) - Disk 1A.dsk|Disk 1A
>Alive (F).7z#Alive (F) - Disk 1B.dsk|Disk 1B

With the current state of m3u support, I can't even get zipped .dsk files to work when the m3u file has this content:
> Alive (F) - Disk 1A.zip
> Alive (F) - Disk 1B.zip

**Comment by DSkywalk** [comment]
"ZIPs are extracted to a temporary directory in saves, bypassing the default frontend extraction."
is a very bad idea...

A core should not bypass the layers already provided by the retroarch. It's something that if you want to do it should be done above (in frontend), or give us the information to do it internally. But cores should not reinvent the wheel...

Thank you for your suggestion as well.

**Comment by DSkywalk** [comment]
Sorry about the other part of the suggestion, I do see it interesting, it would be to put a label on the discs, right? cool :D

You can edit the title or create a different issue with just that part and reopen it :+1:

**Comment by veganvelociraptor** [comment]
I found the original request for this: https://github.com/libretro/RetroArch/issues/10299

It appears to have been suggested as a general Retroarch improvement, but then implemented at a core level? Do you think I perhaps should somehow necrobump that issue thread? :)
