### ISSUE TITLE
cap32 core in Retroarch (Steam version) - Issue Drive A: disc missing

### ISSUE THREAD

**Issue by ElNaipeZZ** [libretro/libretro-cap32#104]
Hello.

I will report a issue.

The cap32 core runs fine in Retroarch (Steam version) but when I load a disk I get the message "Drive A: disc missing" on the emulated Basic.

Retroarch displays "Failed to add disk" message. I tried several .dsk files and they don't run.
I also tried with the autorun option enabled and disabled in the cap32 core settings in Retroarch and they don't run either.

**Comment by DSkywalk** [comment]
@ElNaipeZZ súbeme un DSK que estés usando. Para comprobar primero el fichero :+1:

**Comment by ElNaipeZZ** [comment]
@DSkywalk I uploaded the DSK.
I also replied to you on Twitter. 😉
[Abadia del Crimen, La (Spain).zip](https://github.com/libretro/libretro-cap32/files/7885033/Abadia.del.Crimen.La.Spain.zip)

**Comment by DSkywalk** [comment]
It should be any problem with your playlist or the directory, RA-Steam cannot access some drives/folders.

**Comment by DSkywalk** [comment]
![imagen](https://user-images.githubusercontent.com/560310/150193832-ab66bba6-84f5-43cc-b14a-616f6758f011.png)
![imagen](https://user-images.githubusercontent.com/560310/150193855-e484df45-1516-4ed4-bdd4-f61e5509cbbb.png)
![imagen](https://user-images.githubusercontent.com/560310/150193882-04c2e3ef-5ba5-498b-ab16-9e9c24aeda01.png)

-- ra-steam windows 11
