### ISSUE TITLE
SNA support broken ?

### ISSUE THREAD

**Issue by FabLafarge** [libretro/libretro-cap32#105]
Loading a SNA file seems broken at the moment.
The CPC just sits at the usual BASIC prompt instead of running the snapshot.

**Comment by DSkywalk** [comment]
Tested on lastest retroarch/core (standalone 1.10.0/cap32 - 4.5.2 b8f09a0) and working as expected :+1:

**Comment by FabLafarge** [comment]
Tested again, doesn't work here :

Steps to reproduce :
- Download fresh binaries from: https://buildbot.libretro.com/stable/1.10.0/windows/x86_64/RetroArch.7z
- Load core -> Download a core -> Amstrad - CPC/GX4000 (Caprice32) (ie ver 4.5.2 b8f09a0)
- Load content -> Browser for any SNA file 
- Expected result : CPC emulation started, SNA file loaded and runing (ie game running)
- Actual result : usual BASIC 1.1 prompt, waiting for user interraction

Reproduced on Windows and PSPVita builds.
![02](https://user-images.githubusercontent.com/22907390/151845425-23e609d6-7d04-40fc-9f17-14b16ad25dea.png)
![01](https://user-images.githubusercontent.com/22907390/151845428-35fa03f9-a2cb-4705-bbf1-027575e6cb3f.png)
![03](https://user-images.githubusercontent.com/22907390/151845431-d724ab1e-8fe7-48d6-960e-054e910d3dc2.png)
![00](https://user-images.githubusercontent.com/22907390/151845432-10dc136a-be58-43b5-9dae-bfb587d48b09.png)

**Comment by FabLafarge** [comment]
Further investigation seems to indicate SNA support may be incomplete

Enabling verbose logging and attempting to load produces the following log :

```
SNA Error (18): C:\Temp\Fruity Frank.sna (0)=1
 (1)=1
````

which would indicate this error: ERR_SNA_SIZE


I imagine SNA loading works fine with snapshots generated by the core itself, but will often fail with third party SNAs fetched off the internet

**Comment by FabLafarge** [comment]
Had a dive into the code, and my findings so far are :

- In `cap32.h`, that "+1" violates the SNA fileformat specs (see https://www.cpcwiki.eu/index.php/Format:SNA_snapshot_file_format ) , which means all subsequent data is offset by 1.
Therefore, this core is only compatible with its own SNA and will fail with any SNA created with a third party emulator.

```
typedef struct {
   char id[8+1];
   char unused1[8];
   unsigned char version;
```

- RAM data compression is indeed unsupported which in itself is not a violation of the specs, but severly limits the amount of third party SNAs that could be loaded if the previous bug were fixed.

**Comment by FabLafarge** [comment]
Good news: I made a build changing this
```
typedef struct {
   char id[8+1];
   char unused1[8];
   unsigned char version;
```

to this 
```
typedef struct {
   char id[8+1];
   char unused1[7];
   unsigned char version;
```

and the core now loads successfully thirdparty uncompressed snapshots :)

**Comment by DSkywalk** [comment]
We may have to make an old SNA converter, but it can be prepared as a contrib with a small python script. I prefer your solution and that the SNA is as the format that was decided as standard. Thank you very much.
