### ISSUE TITLE
Switch DSK drive A/B?

### ISSUE THREAD

**Issue by Marc34** [libretro/libretro-cap32#11]
Hi,

I don't understand how to load other disks. I use VKBD and « dsk », but nothing happens.

Thank for your help.

**Comment by r-type** [comment]
Do you mean 
1) load side B after booting side A 
2) or just launch another disc ?

If 1 , you have to go to GUI (pressing GUI on vkbd then choose Floppy or shortcut F8 on keyboard ) then you can choose the desired side B for the Floppy DiskA. 
then returning to game by pressing Back to main menu / OK .

If 2 , you have to reset first to comeback to basic (not implemented yet on VKBD have to use the dedicated shortcut R button ,then go to GUI or F8 to choose new game and when returning to emu the autoboot should launch the game.

BTW, there are some bugs/mistake with mapping and it is not optimal yet.
And the DSK on vkbd is for swap drive A/B but not used for now .

**Comment by Marc34** [comment]
Sorry, I wasn't aware of this ambiguity. I mean "load side B after booting side A". Thank for your answer, I didn't notice the « GUI » on vkdb.
