### ISSUE TITLE
[enhancement] SRAM DSK support

### ISSUE THREAD

**Issue by DSkywalk** [libretro/libretro-cap32#111]
# SRAM disk save support
* related to #108

@Jamiras: _If a game has in-game save support, that must be managed by the libretro SRAM interface. Modifying the original files will cause the hashing algorithm to no longer be able to identify the game on subsequent loads._

Requeriments:
 - doesn't allow to "corrupt" a DSK
 - DSK diff system

**Comment by Snapouille** [comment]
@DSkywalk: do you manage to use the in-game save?
I tried with Shadow of Sergoth (quit and save) and "Superpix" (logically autosave)
and the both doesn't work.

I try these saves to go with the retroachievements hardcore mode.

**Comment by DSkywalk** [comment]
@Snapouille As you can see since this is an ISSUE/Enhancement it is something that needs to be programmed :wink:

**Comment by Snapouille** [comment]
@DSkywalk anything new about that issue?

**Comment by DSkywalk** [comment]
# WIP

Play a game, save to DSK:
```
[INFO] [slots::dsk_diff] HEAD [tracks 40, sides 1]
[DEBUG] [slots::dsk_diff_track] [18/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 18/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_track] [21/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 21/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_track] [22/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 22/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_track] [27/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 27/40, side 0/0, sectors: 15, size: 3840
[INFO] [slots::dsk_diff] DSK diff Saved: /.../.config/retroarch/saves/game.dsk.sav
```

Reopen RA and Reload game DSK:
```
[INFO] [slots::dsk_diff_load] Loading DSK changes saved at: /.../.config/retroarch/saves/game.dsk.sav
[DEBUG] [slots::dsk_diff_load] track: 18/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_load] track: 21/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_load] track: 22/40, side 0/0, sectors: 15, size: 3840
[DEBUG] [slots::dsk_diff_load] track: 27/40, side 0/0, sectors: 15, size: 3840
```

Test using AMSDOS/BASIC DSK:
1 - basic test DSK:
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/ce529e8f-47d0-4222-8fa9-fab93d4e5591)

2 - Create a simple program and save to DSK
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/167b8fac-6934-4013-a0dc-31e9eca1f98a)

3 - New Catalogue:
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/bfab24b6-1a4a-40b7-835c-e6c1aed4ecb7)

Closing RA:
```
[INFO] [slots::dsk_diff] HEAD [tracks 40, sides 1]
[DEBUG] [slots::dsk_diff_track] [0/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 0/40, side 0/0, sectors: 9, size: 4608
[DEBUG] [slots::dsk_diff_track] [4/0] Data changed.
[DEBUG] [slots::dsk_diff] track: 4/40, side 0/0, sectors: 9, size: 4608
[INFO] [slots::dsk_diff] DSK changes saved: /.../.config/retroarch/saves/mode3tst.dsk.sav
```

Reopen RA:
```
[libretro INFO] [computer_load_file] Disk (1) inserted into drive A: ../assets/DISKS/mode3tst.dsk
[INFO] [slots::dsk_diff_load] Loading DSK changes saved at: /.../.config/retroarch/saves/mode3tst.dsk.sav
[DEBUG] [slots::dsk_diff_load] track: 0/40, side 0/0, sectors: 9, size: 4608
[DEBUG] [slots::dsk_diff_load] track: 4/40, side 0/0, sectors: 9, size: 4608
```

![imagen](https://github.com/libretro/libretro-cap32/assets/560310/b62532f2-4ddb-453d-bf8a-a9af32fab3ed)

**Comment by DSkywalk** [comment]
@Snapouille @Jamiras :eyes:

**Comment by Jamiras** [comment]
>  Is it necessary to use these functions for the achievements, or is the requirement just to not modify the original DSKs?

Just to not modify the original files. We hash the game files when they're loaded to ensure the player isn't using a modified version of the game (hacked code, trainer, etc) or an incompatible version (memory may shift between releases). If saving to the disk modifies the file, we can't tell that it's because the user saved to the disk and assume they're using a bad version of the game.

The libretro SRAM interface is designed for managing volatile data between sessions. Technically, you don't have to use it - you could put the modified files somewhere else. But using the SRAM interface lets the frontend manage where the persistent files get stored.

It looks like you're writing files directly to the libretro save directory:
```
[INFO] [slots::dsk_diff] DSK diff Saved: /.../.config/retroarch/saves/game.dsk.sav
```

I imaging this should work, but I don't know enough about how libretro manages it directories to know when the directory will be created, or what permissions it will have across the ecosystem of operation systems RetroArch suppports.

**Comment by Jamiras** [comment]
> I don't know if it is a requirement to use retro_get_memory_size/retro_get_memory_data, because it is a DSK and those are changes to a floppy (or some floppys) I think is too complex for a single memory buffer.

The simplest solution is just to return a buffer large enough to hold the entire disk and just dump the whole disk into the buffer. There's probably some ways to optimize that so it only captures the disk when it's been modified, but I'm less certain about how the data gets passed back in to the core - if the buffer size needs to be big enough to hold a fully modified disk, it becomes pointless to even check if the disk is modified before flushing it through the SRAM API.

**Comment by DSkywalk** [comment]
Yes, the SRAM system is designed for simple memories and that is why I created a custom DSK-DIFF system. We have access to the path where the user saves his games, in the case of the example I have it configured in a different path to where the ROMs are. 

Anyway if your requirement is not to modify the original file, then I can pass the new feature to the cleaning phase and final testing. Thank you very much!!! :+1:

**Comment by DSkywalk** [comment]
Testing with Shadows of Sergoth
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/c97626e6-41b4-4188-9d99-539d0bf7b59b)
