### ISSUE TITLE
[libretro-database] Amstrad CPC - clean-cpc-db

### ISSUE THREAD

**Issue by DSkywalk** [libretro/libretro-cap32#112]
This issue serves to organise the work of creating a new libretro database for CPC computer.

More info at: https://github.com/libretro/libretro-database/issues/1282

[![clean-cpc](https://user-images.githubusercontent.com/560310/162202108-23de243a-178f-4531-9ad4-b854e400b5b9.png)](https://archive.org/search.php?query=subject%3Aclean-cpc-db)

| LETTER | assigned | status |
|----------|-------------|-------------|
| # | @DSkywalk | RC 1 |
| A | @DSkywalk | RC 1 |
| B | ^Morgoth^ | RC 1 |
| C | @DSkywalk | RC 1 |
| D | @DSkywalk | RC 1 |
| E | @DSkywalk | RC 1 |
| F | ^Morgoth^ | RC 1 |
| G | @DSkywalk | RC 1 |
| H | ^Morgoth^ | RC 1 |
| I | @DSkywalk | RC 1 |
| J | @DSkywalk | RC 1 |
| K | ^Morgoth^, televandalist | RC 1 |
| L | @DSkywalk | RC 1 |
| M | Macarro, ^Morgoth^ | RC 1 |
| N | ^Morgoth^ | RC 1 |
| O | ^Morgoth^ | RC 1 |
| P | ^Morgoth^ | RC 1 |
| Q | @DSkywalk | RC 1 |
| R | @DSkywalk | RC 1 |
| S | @DSkywalk | RC 1 |
| T | ^Morgoth^ | RC 1 |
| U | @DSkywalk | RC 1 |
| V | @DSkywalk | RC 1 |
| W | @DSkywalk | RC 1 |
| X | @DSkywalk | RC 1 |
| Y | @DSkywalk | RC 1 |
| Z | @DSkywalk | RC 1 |

# how to
We are using the [tosec list as base gamelist](https://github.com/libretro/libretro-database/blob/master/metadat/tosec/Amstrad%20-%20CPC.dat) to build no-intro-cpc new disk-set.
* Download the original version of cpc-power. (do not use cpc-rulez 'cause adds junk data). [Naming examples](https://www.tosecdev.org/tosec-naming-convention#_Toc302254975):
  * 007 - A View To A Kill (1985)(Domark).dsk
  * 1943 - The Battle of Midway (1988)(US Gold)[a].dsk (alternative version)
  * 2112 AD (1986)(Design Design Software)(M4)[v2].dsk (Multilanguage and V2 original version)
* If it doesn't exist then use a version with **NO trainer** or **cracker screen**. Add to Filename **[cr]** label. Examples:
  * 3 Guerra Mundial (1989)(Pactum)(es)(Side A)[cr].dsk
  * 2112 AD (1986)(Design Design Software)(M4)[cr Chany].dsk
* If it doesn't exist a clean release then mark as **[miss]** label.
* If autorun do not detect correctly the disc mark as **[fail]** label.

**Comment by RobLoach** [comment]
Would this be torrentzip versions of TOSEC?

**Comment by DSkywalk** [comment]
Hello Rob!
Well, the truth is that after getting to work we have seen that TOSEC was not very well worked for 8-bit computers, wrong names, wrongly named companies, wrong years...

I'm happy that we have started this work even if it had to be done by hand and checking one by one. We'll share it in archive.org and I'll prepare a dat ready for you :+1:

**Comment by DSkywalk** [comment]
@RobLoach I've released the first beta and you have the dat available in the [clean-cpc-db](https://github.com/clean-cpc-db) repository. You can take a look at it and let me know how you see it, or if you see that you might need something else?

Thanks,  it's almost there!

**Comment by DSkywalk** [comment]
published RC1

**Comment by DSkywalk** [comment]
finally we published V1.0 :+1:
