### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by Dako9767845** [libretro/libretro-cap32#113]
I'm trying to boot up cap32 but the screen is black, the's but other than that cute can't seem to show anything

**Comment by DSkywalk** [comment]
Well, I need more info to help you:

retroarch version?
core version/hash?
s.o.?

Any game launched?

Thanks!

**Comment by Dako9767845** [comment]
I am using version 1.10.2

the core is Caprice32 and the hash is ef0ee89 HI

and pretty much any game yep

**Comment by DSkywalk** [comment]
Operating System? Video Driver?
Other cores working for you?

And please create a log and upload to this issue:
https://docs.libretro.com/guides/generating-retroarch-logs/

Thanks

**Comment by Dako9767845** [comment]
I followed what you said and still noting show up 

another core I try is crocoDS and it worked but a lot of people warned not to use crocoDS for achievements 

and the game is called The Abbey of Crime 8742c9b1

**Comment by DSkywalk** [comment]
First, please what is your operating system? 

![imagen](https://user-images.githubusercontent.com/560310/161033646-9157c381-0e2f-40fa-b0fc-3e71ca86c2da.png)

Your rom is not supported to play Abbey of Crime:
Download the original version from cpc-power or cpc-rulez. Any other DSK file do not work with achievements.

**Comment by Dako9767845** [comment]
here are the specs
![Speccy](https://user-images.githubusercontent.com/102679943/161035370-7572c6ff-00b8-4b03-984a-732b6dba97e8.PNG)
 
I've used the site you and I think thing 

my RA Checksum: e5eb771fbdc275ad2bcc219845bf7055

**Comment by DSkywalk** [comment]
Your checksum is perfect :100: 

It is a somewhat old operating system but there should be no problem. Can you generate the log for me so I can see exactly what happens when you start the emulation? I told you above how to do it :+1:

**Comment by Dako9767845** [comment]
I change the video to vulkan and now retroarch does it want to load anymore

**Comment by DSkywalk** [comment]
delete your retroarch.cfg to clean start or delete vulkan from the cfg file. (find them and remove)

**Comment by Dako9767845** [comment]
Hey man, just try some other game and played around with the video options, and still, nothing is showing

**Comment by DSkywalk** [comment]
Tomorrow I'll prepare a test build for you 👍

**Comment by DSkywalk** [comment]
@Dako9767845 I still need it [a complete log](https://github.com/libretro/libretro-cap32/issues/113#issuecomment-1084132464), 

but try this builds:

* http://david.dantoine.org/ficheros/ra/cap32_libretro-core16bits_w32.zip
* http://david.dantoine.org/ficheros/ra/cap32_libretro-core16bits_w64.zip

**Comment by Dako9767845** [comment]
ok, download the builds and it worked, 

thank you very much

**Comment by DSkywalk** [comment]
I added an option to allow configure your depth, by default the core depth is 16bits (more compatible mode).
