### ISSUE TITLE
M3U clean version, a green disk icon does not appear

### ISSUE THREAD

**Issue by cesarpuig** [libretro/libretro-cap32#118]
Hello.

If you run a game included in clean-cpc-db, from an M3U file, either because it contains multiple discs or because you have to specify a command to run it, a green disk icon does not appear.
![172237853-0a18ebee-be5e-4dec-90fa-e4ca7b77a2d7](https://user-images.githubusercontent.com/30637939/178117133-94b5c4bf-30d5-4e6e-a7eb-4449dde6f35c.png)

Gracias, por el gran trabajo realizado con este emulador.

**Comment by DSkywalk** [comment]
The multipart/crc is not ready yet i'm working on it :+1: 

Gracias a ti :tada:
