### ISSUE TITLE
GX4000 / Burnin Rubber - Regression, visual glitchs after update to a1e4a79

### ISSUE THREAD

**Issue by TiBeN** [libretro/libretro-cap32#119]
Hi, just updated my libretro cores (the official way through the gui).

Seems there is a regression in GX4000 emulation, Burnin Rubber has glitches and is now unplayable, see screenshots.

![Burnin' Rubber  CPC+  (E) - Red Label-220810-130247](https://user-images.githubusercontent.com/910115/183886217-89af40fd-c137-4ac4-bb99-c139bee7656e.png)
![Burnin' Rubber  CPC+  (E) - Red Label-220810-130232](https://user-images.githubusercontent.com/910115/183886222-b1eda970-6530-4e81-b749-8c3fef651ece.png)

Additional infos:
System: ArchLinux (official pacman retroarch package)
Retroarch version: 1.10.3

My GX4000.opt (carts directory config):

```
cap32_advanced_green_phosphor = "15"
cap32_autorun = "enabled"
cap32_combokey = "select"
cap32_db_mapkeys = "enabled"
cap32_floppy_sound = "enabled"
cap32_gfx_colors = "16bit"
cap32_lang_layout = "english"
cap32_model = "6128+ (experimental)"
cap32_ram = "128"
cap32_retrojoy0 = "auto"
cap32_retrojoy1 = "auto"
cap32_scr_intensity = "8"
cap32_scr_tube = "color"
cap32_statusbar = "onloading"
```
Rom:

```
$ md5sum Burnin\'\ Rubber\ \[CPC+\]\ \(E\)\ -\ Red\ Label.cpr 
0a527172192c50c2fd2567bdbcb7acd0  Burnin' Rubber [CPC+] (E) - Red Label.cpr
```

**Comment by TiBeN** [comment]
OK, switching 24bits color depth fixes the issue. I keep the issue opened as it is a little counter-intuitive at first glance. 
(not sure everybody will look at this option to fix this)

**Comment by DSkywalk** [comment]
ATM CPC+ emulation need 24bits color depth, sorry :+1: 

We marked CPC+ as experimental because is incomplete.

**Comment by TiBeN** [comment]
OK. I often play Burnin Rubber and i would say the emulation is pretty good :)
Thank for you feedback.
