### ISSUE TITLE
can't use joystick in gui menu

### ISSUE THREAD

**Issue by rockaddicted** [libretro/libretro-cap32#12]
Hi @r-type 
I've a question about the gui. I set my input type on Amstrad Joystick, I've access to vkbd and gui menu, no problem about that.
But once, in the gui menu, I can't use my gamepad to interact with it, as I can do with libretro-hatari core, for example.
So, have I missed something or it is a known problem ?

**Comment by r-type** [comment]
i have to look but i think its because i have to take out
i=2;//mouse/joy toggle  of the pauseg=0 if.


```
 i=2;//mouse/joy toggle
   if ( input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, i) && mbt[i]==0 )
      mbt[i]=1;
   else if ( mbt[i]==1 && ! input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, i) ){
      mbt[i]=0;
      MOUSE_EMULATED=-MOUSE_EMULATED;
   }
```

**Comment by r-type** [comment]
if you can test , can't access a joystick before tomorrow

**Comment by rockaddicted** [comment]
Yep I'll test that.
Thanks :wink:

**Comment by rockaddicted** [comment]
Perfect, that work.
Thank you
