### ISSUE TITLE
Input issue with game: Target Renegade

### ISSUE THREAD

**Issue by ThatsSasso** [libretro/libretro-cap32#120]
Game starts fine but there is no left or right movement. I am using sixaxis controller. All other buttons work.

**Comment by DSkywalk** [comment]
Have you defined the controls for playing?

Many games work directly by selecting JOYSTICK, others need you to redefine them or you can contribute your RMP to add to our core:

* [Contribute with your RMP files](https://github.com/libretro/libretro-cap32/wiki/%5Bcolaborate%5D-create-a-new-RMP-for-your-favorite-game!)

**Comment by ThatsSasso** [comment]
Hi thanks for your reply. I've tried everything, selecting amstrad joystick
etc. But nothing fixes it. I managed to use the games own keyboard mapping
to redefine keyboard controls and mapping the gamepad to the keyboard
inputs I chose, and selecting amstrad keyboard as my controller. There does
seem to be a problem with the input functions of the amstrad core. Pressing
select does not bring up the on-screen keyboard and my usb keyboard is not
recognized either. Joystick only goes up or down, no left or right. Thanks
for your help.

**Comment by DSkywalk** [comment]
I think we are talking about different functionalities. I have the feeling that something is not configured properly, but I must assume that with the other AR cores you don't have a problem :+1: 

 Let's do a simple test. My controller configuration: 

![imagen](https://user-images.githubusercontent.com/560310/192007866-b86b2776-73c5-40d9-a6e6-ef87eb6929f4.png)
_Quick Menu > Controls > Port 1 Controls_

![imagen](https://user-images.githubusercontent.com/560310/192008101-3eaebe37-fbe5-4ee5-a07f-ac4adc7c0e15.png)
_Quick Menu > Options_

Start the core without any game loaded...

![imagen](https://user-images.githubusercontent.com/560310/192008600-5325c36a-e04c-4c24-bf38-19f56d19f402.png)

... and check that you can paint all these characters
![imagen](https://user-images.githubusercontent.com/560310/192008327-301e7ddd-e799-419d-9430-7ac2e6691e06.png)

**Comment by ThatsSasso** [comment]
Hi I have the same configuration except under controller configuration
there is no "auto" option. There is 3 options: joystick, qaop, and
incentive. I chose qaop because it is the only one that seems to work.
Pressing the d-pad gives me:qaop. Pressing the buttons gives me: b space y
n.
Thanks

**Comment by ThatsSasso** [comment]
Hi I tried selecting joystick and I got the same readout as your
screenshot. Just going to test in the game. Thanks

**Comment by DSkywalk** [comment]
Great, if you dont have "auto" config, your core is outdated. Which device
do you use? You should try to update it to get the latest changes :)

**Comment by ThatsSasso** [comment]
Hi I'm using ps3 unofficial community edition beta. I regularly update the
cores.
Thanks

**Comment by DSkywalk** [comment]
Mmmf, the config "auto" update it would be published about... 4 months? 😅✨
