### ISSUE TITLE
Poor performance with the original Raspberry Pi B (256Mb Model)

### ISSUE THREAD

**Issue by anetwalker** [libretro/libretro-cap32#121]
I've been testing the emulator provides with Retropie 4.8 for RP1 B, and It is noted that the sound does not play at normal speed, During the play of the game it is also observed that the speed is lower than the original.
I've overclocked the RP1, change the render resolution and get the same results, also I've update the emulator from source and it doesn't improve.

Could you help me? 

Thanks

**Comment by DSkywalk** [comment]
The CPC has many tricks that require a processor to be emulated, but I think it should work well on the hardware you mention, I've got almost fullspeed on the DS, I don't understand how it can't be done on a rasp. Try compiling with these flags que han ido muy bien con la evercade:

	CFLAGS := -DFRONTEND_SUPPORTS_RGB565  -DLOWRES -DINLINE="inline" -DM16B
	CFLAGS += -falign-functions=1 -falign-jumps=1 -falign-loops=1
	CFLAGS += -fomit-frame-pointer -ffast-math	
	CFLAGS += -funsafe-math-optimizations -fsingle-precision-constant -fexpensive-optimizations
	CFLAGS += -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-unroll-loops

**Comment by anetwalker** [comment]
Hi David, thanks for your advice. Unfortunately I have a limited knowledge programming. Could you guide me how to carry out what you suggest me?

**Comment by DSkywalk** [comment]
Do you know how to copy a file to the pi and run it? I can compile a hello-world-sample to see if it works for you and if it works fine use those flags for the core, see what we can improve :+1:

**Comment by anetwalker** [comment]
Yes, I have full ssh access to the RP1 and I can run whatever you want. Thanks for your help!

**Comment by DSkywalk** [comment]
Please test :tada:  
# arm-linux-gnueabi 
## Compatible cflags: -march=armv6 -mfloat-abi=hard -mfpu=vfp
[cap32_v6fp_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690570/cap32_v6fp_libretro.zip)

## Optimized cflags: -march=armv6zk -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp
[cap32_v6zk_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690571/cap32_v6zk_libretro.zip)

:smiley:

**Comment by DSkywalk** [comment]
# lowres/24bits

[cap32_hfv6j-24_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690621/cap32_hfv6j-24_libretro.zip)
[cap32_v6fp-24_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690625/cap32_v6fp-24_libretro.zip)

#hires/24bits
[cap32_v6fp-24h_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690627/cap32_v6fp-24h_libretro.zip)
[cap32_hfv6j-24h_libretro.zip](https://github.com/libretro/libretro-cap32/files/9690631/cap32_hfv6j-24h_libretro.zip)

Try not to get confused with so many names and tell me how each of the core versions compiled for RPi1/B works for you.

Thanks!

**Comment by anetwalker** [comment]
Thanks David, I have been testing some of the libraries you provide me. Unfortunately I'm getting an error when launch the rom from EmulationStation:

pi@retropie:/opt/retropie/configs/amstradcpc $ cat /dev/shm/runcommand.log
Parameters:
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-caprice32/cap32_libretro.so --config /opt/retropie/configs/amstradcpc/retroarch.cfg "/home/pi/RetroPie/roms/amstradcpc/Abu Simbel Profanation.zip" --verbose --appendconfig /dev/shm/retroarch.cfg
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirigiendo archivo de guardado a "/home/pi/RetroPie/roms/amstradcpc/Abu Simbel Profanation.srm".
[INFO] Redirigiendo archivo de guardado rápido a "/home/pi/RetroPie/roms/amstradcpc/Abu Simbel Profanation.state".
[INFO] === Build =======================================
[INFO] Capacidades:
[INFO] Built: Nov  2 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-caprice32/cap32_libretro.so"
[ERROR] Failed to open libretro core: "/opt/retropie/libretrocores/lr-caprice32/cap32_libretro.so"
Error(s): /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /opt/retropie/libretrocores/lr-caprice32/cap32_libretro.so)


It seems that I need a newer version of libm.so.6.

I will find out if there is any way to update it.

**Comment by DSkywalk** [comment]
ok, old devkit... try this build:
[cap32_c6v_libretro.zip](https://github.com/libretro/libretro-cap32/files/9699956/cap32_c6v_libretro.zip)

**Comment by DSkywalk** [comment]
I have added in the last update different flags for RPI, you can tell the Retropie guys that they can use them now and check that with the official build it works for you too (and more importantly it works for everyone else). If you have any questions, feel free to reopen this ISSUE.

![imagen](https://user-images.githubusercontent.com/560310/193882221-72b969b3-7f1b-44e5-b001-df271de416ab.png)
Regarding your problem, in the core options activate the 6128+, but keep in mind that in 16bits it will give you problems. I'll prepare a 24bit build for you, otherwise it will give you graphic errors ( see #119 ). 

Test this build (24bits for RPI1 B)
[cap32_v6b24_libretro.zip](https://github.com/libretro/libretro-cap32/files/9709153/cap32_v6b24_libretro.zip)
 [-march=armv6zk -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp]

Muchas gracias por tu apoyo, me apunto la cerveza :beers:
