### ISSUE TITLE
Crtc versions 

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-cap32#123]
I there any way to change the CRTC version (e.g. UM6845, UM6845, HD6845S) for difficult demos compatibility?

**Comment by DSkywalk** [comment]
Caprice32 does not include CRTC configurations, so this will not be addressed for the time being, sorry.  What I can tell you is that I'm going to work on trying to improve the floppy implementation, so that more protections will work.

Thanks for your feedback :+1:

**Comment by Vweber73** [comment]
Thanks a lot, I understand! :)
About tuning the keyboard transparency and removing the mouse pointer (see my comments on the closed issue), and possibly having keypress visual/haptic feedback, do you have any comment?
Many thanks and best regards

**Comment by DSkywalk** [comment]
Hello again @Vweber73 !

Haptic is not implemented in RA and I don't consider the rest to be important right now either, degrees of transparency would affect the optimisation and I wouldn't remove the cursor without having some other feedback on the keys, apart from the fact that it's not annoying at all, it just goes where you clicked and serves as a reference :mag:

**Comment by Vweber73** [comment]
Got it for transparency level, the one you chose is good enough, and for the haptic and visual. feedback 
Regarding the mouse pointer, well, it's ennoying in a sense that sometimes you get missed key strokes on the Enter key. Now maybe the mouse pointer is not the cause of that, but I suspect it is, sometimes you have to press twice and it seems that it is because the first press positions the pointer... I may be wrong, since the problem only seems to occur with the Enter key and not the others..?
Thanks a lot and regards

**Comment by DSkywalk** [comment]
Note that what I receive from the emulator are the "clicks" sent to me by the frontend, I don't have full control of the pointer. If the UI gives me a movement, I move it. If the UI gives me a touch, I press the key. What you say is how the system works in Android and I can't do too much at the moment. Anyway I'll try to see if I can improve it, but believe me the pointer has nothing to do with it, it's just the feed back I get from the retroarch UI.

CU! :dancers:

**Comment by Vweber73** [comment]
Got it, many thanks!
Cheers
