### ISSUE TITLE
Assign key as hotkey does not work

### ISSUE THREAD

**Issue by cesarpuig** [libretro/libretro-cap32#124]
Hello.

I have number 3 configured as hotkey `input_enable_hotkey = "num3"`. If I run a game that uses it, it doesn't work for me, like Army Moves, which uses the number 3 to start the game. If I press it from the virtual keyboard it doesn't work either.

My retroarch version is 1.10.0, and caprice32 is the latest source.

Thanks a lot

**Comment by DSkywalk** [comment]
Maybe you need activate focus mode?
Anywsy take a look to our RMP files, maybe you could contribute it :)

Cu!

**Comment by DSkywalk** [comment]
Entiendo que te refieres a esto
![imagen](https://user-images.githubusercontent.com/560310/194227039-af22681e-b891-4b16-90e3-f4663b33d7bb.png)

Si activas el focus, puedes escribir el 3
![imagen](https://user-images.githubusercontent.com/560310/194226909-b0e4d095-e421-4859-9fb5-f1ba72ff387d.png)

El focus se configura aquí:
![imagen](https://user-images.githubusercontent.com/560310/194227130-a398c89b-0f82-40cb-8752-f5b2dc9d741e.png)

De todas formas intentaré añadirte el Army Moves en el siguiente update del RMP.
Si sigues con la duda reabre la Issue :+1:

**Comment by cesarpuig** [comment]
Hola David.

El modo Game Focus ¿no debería afectar al funcionamiento del resto de mis controles?, solo me esta afectando al que tengo asignado como Hotkey. Independientemente de que tenga o no activado el modo Game Focus, el resto de pulsaciones son reconocidas, como:

`input_player1_a = "c"`
`input_player1_b = "d"`
`input_player1_down = "down"`
`input_player1_gun_select = "num0"`
`input_player1_gun_start = "num1"`
`input_player1_l = "e"`
`input_player1_l2 = "ctrl"`
`input_player1_l3 = "space"`
`input_player1_left = "left"`
`input_player1_r = "f"`
`input_player1_r2 = "shift"`
`input_player1_r3 = "num5"`
`input_player1_right = "right"`
`input_player1_select = "num0"`
`input_player1_start = "num1"`
`input_player1_up = "up"`
`input_player1_x = "b"`
`input_player1_y = "a"`

`input_enable_hotkey = "num3"`

El num3 lo utilizo como select del player 2 y como hotkey.

Estos son mis parámetros de configuración de Caprice 32:

`cap32_advanced_green_phosphor = "15"`
`cap32_autorun = "enabled"`
`cap32_combokey = "select"`
`cap32_db_mapkeys = "enabled"`
`cap32_floppy_sound = "enabled"`
`cap32_gfx_colors = "16bit"`
`cap32_keyboard_transparency = "disabled"`
`cap32_lang_layout = "spanish"`
`cap32_model = "6128"`
`cap32_Model = "6128"`
`cap32_ram = "128"`
`cap32_Ram = "128"`
`cap32_retrojoy0 = "joystick_port1"`
`cap32_retrojoy1 = "joystick_port2"`
`cap32_scr_intensity = "8"`
`cap32_scr_tube = "color"`
`cap32_statusbar = "onloading"`

Por cierto ha habido una actualización reciente en la que se incluye un rmp de Army Moves, no se si es que no esta terminado o no se configurarlo pero no consigo que me funcionen los controles.

Un saludo y perdón por las molestias.

**Comment by DSkywalk** [comment]
La verdad es que no soy capaz de reproducir tu problema. Las hotkeys se ejecutan en la interfaz  lugar que mandarlo al CORE, la pulsación no llega al emulador. Por eso hay que activar el focus, pero solo afecta al teclado, no a mandos... Lo curioso es que veo que estás configurando teclas ¿es un JPAC? si es un JPAC te afectará claro, por que creo que lo usan como si fuera teclado.

Es el funcionamiento de RA, no sé si te podré ayudar mucho compa :_

**Comment by cesarpuig** [comment]
Hola David.

>¿es un JPAC?

No, es un [UHid](https://www.ultimarc.com/control-interfaces/u-hid-en/u-hid/), pero a efectos es lo mismo, creo, el funcionamiento es como un teclado.

¿El teclado no es compatible con la función de remapeo de los controles que estas introduciendo?.
