### ISSUE TITLE
[Feature request] - Phazer, Gunstick, Magnum light gun emulation

### ISSUE THREAD

**Issue by Tovarichtch** [libretro/libretro-cap32#125]
Hello devs,

Title is self-explanatory. Currently, several CPC+/GX4000 emulators already have those light gun support. Recently, [caprice32](https://github.com/ColinPitrat/caprice32/issues/34) implemented it (except the gunstick which works differently) for the various light gun games and it works really well. There are around 25 gun games.

Can it be integrated to libretro-cap32 ?

Thanks in advance !

**Comment by DSkywalk** [comment]
Hello @Tovarichtch I'm the developer of Wiituka, I'll port my code here no problem, I had already planned it. But right now I'm busy with [RMP configurations](https://github.com/libretro/libretro-cap32/wiki/RMP:-Done) :+1:

**Comment by Tovarichtch** [comment]
Glad to read it! I didn't know.

**Comment by Darknior** [comment]
> Hello @Tovarichtch I'm the developer of Wiituka, I'll port my code here no problem, I had already planned it. But right now I'm busy with [RMP configurations](https://github.com/libretro/libretro-cap32/wiki/RMP:-Done) +1

Thanks a lot, i'm very impatient to try it too :)

**Comment by Snapouille** [comment]
> Hello @Tovarichtch I'm the developer of Wiituka, I'll port my code here no problem, I had already planned it. But right now I'm busy with [RMP configurations](https://github.com/libretro/libretro-cap32/wiki/RMP:-Done) 👍

Good news, thank you, can't wait to test this

**Comment by Tovarichtch** [comment]
Simple screenshot, a small crosshair, but already exciting ! Can't wait to try that out.

**Comment by DSkywalk** [comment]
Need more work but...

https://user-images.githubusercontent.com/560310/206310392-27bf7774-4477-4a4d-b948-6d9a138f4691.mp4

**Comment by DSkywalk** [comment]
Feature done, gunstick and phaser emulation working :christmas_tree: :star_struck: 

Merry Christmas :)

**Comment by Tovarichtch** [comment]
What!? With the Loriciel Phaser too!? How in the world you did that! That's a wonderful gift. Thank you very much! I will try them as soon as I have time.

**Comment by Tovarichtch** [comment]
Ah nvm my last comment, this light gun is still missing (only 3 games supported it) : 

https://www.cpcwiki.eu/index.php/Loriciel_Phaser_(West_Phaser)

Can it be added in the future?

**Comment by DSkywalk** [comment]
It's really two games Steve, it's the same. The truth is that it would be a low priority, I would like to improve some points of the gunstick emulation in the future before I start with a new system.

**Comment by Tovarichtch** [comment]
No hurry at all. You did an amazing emulation already!

One quick question : for GX4000, the pha**_z_**er light gun is the same as "pha**_s_**er" for Amstrad CPC?

**Comment by DSkywalk** [comment]
Well, try it and let me know :wink:

**Comment by DSkywalk** [comment]
demo!

https://user-images.githubusercontent.com/560310/209864844-286a2604-1838-48d4-bb00-0e8a584d0576.mp4

**Comment by phasermaniac83** [comment]
Hi! I can't get it to work in windows 10 and Retroarch cap32 4.5.4.
Activated Lightgun in port 1 and checked gunstick/phaser and show crosshair in core options
Running in Hires mode as I've read Gunstick won't work in lowres mode. Only gunstick suffers this?
Tried with a retroarch clean install,
Tried changing driver from rawinput to dinput,
Tested gunstick and phaser games, changing the Lightgun>input core option
Games start fine, but I can't get the crosshair to show and mouse left button don't do anything. Also tested with lightgun in another pc
It's strange as I have other cores' lightguns working fine so it doesn't seem to be a controller configuration problem
Any clue? thanks!

**Comment by Tovarichtch** [comment]
I confirm and reproduce the issue on Linux too

**Comment by phasermaniac83** [comment]
I downloaded an old cap32 core (17/03/2023) and it works for player 1, so it seems to be a problem with some update.
There are some gunstick 2p games (to play 2 lightguns at same time): Solo, Mike Gunner, Trigger
In retroarch with cap32 core I can select lightgun in p1 and p2, but only p1 works. 
There are other cores that support this with rawinput. Can you @DSkywalk add this please?
I have been  searching and there is no way (but real hardware) to play these games with 2 guns, and there where ports to spectrum, msx... but there is no emulator that supports this feature
Thanks!

**Comment by DSkywalk** [comment]
Thanks for the report @phasermaniac83

**Comment by DSkywalk** [comment]
issue moved to #141

**Comment by DSkywalk** [comment]
Fixed! :)

**Comment by DSkywalk** [comment]
> In retroarch with cap32 core I can select lightgun in p1 and p2, but only p1 works.
> There are other cores that support this with rawinput. Can you @DSkywalk add this please?

Please create an issue with that enhancement and some games to test :+1:
