### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by Marc34** [libretro/libretro-cap32#13]
Hi
When I compile on windows 10 (all seems to work with MinGW), cap32 is unable to see the dsk files and it can't load archives.

**Comment by Marc34** [comment]
In fact, RetroArch is unable to load the dll file.

**Comment by stephvax** [comment]
Hello, I can compile it too, but retroarch seems to exit soon after the core loading.
Could you share your dll build please ?

**Comment by stephvax** [comment]
I finally got a working build.
Autoload doesn't seem to work with any of the games I tried (about 15 different games), have to launch games by hand.
Autoload does work with retropie though.

**Comment by Marc34** [comment]
It seems that there is nobody to maintain cap32.

**Comment by r-type** [comment]
It seems that your are the only one who have such problem with this core.
I cant fix what i cant reproduce.

**Comment by Marc34** [comment]
Sorry to be a problem :) I have deleted windows and reinstalled linux, and all work again now.

**Comment by r-type** [comment]
Lol

I ll try a windows 10 build soon , with the last comits to see if i can reproduce the pb.
