### ISSUE TITLE
Failed to clone

### ISSUE THREAD

**Issue by fg1998** [libretro/libretro-cap32#133]
When using

git clone --recursive --depth 1 --shallow-submodules --branch master "https://github.com/libretro/libretro-cap32.git" "/home/fgarcia/RetroPie-Setup/tmp/build/lr-caprice32"

Get this error
error: Server does not allow request for unadvertised object f5e2cd77c88d9f792562888d2b70c5a396bfbf7a
Fetched in submodule path 'cmocka', but it did not contain f5e2cd77c88d9f792562888d2b70c5a396bfbf7a. Direct fetching of that commit failed.

---- complete result message 

git clone --recursive --depth 1 --shallow-submodules --branch master "https://github.com/libretro/libretro-cap32.git" "/home/fgarcia/RetroPie-Setup/tmp/build/lr-caprice32"
Cloning into '/home/fgarcia/RetroPie-Setup/tmp/build/lr-caprice32'...
remote: Enumerating objects: 594, done.
remote: Counting objects: 100% (594/594), done.
remote: Compressing objects: 100% (488/488), done.
remote: Total 594 (delta 163), reused 388 (delta 91), pack-reused 0
Receiving objects: 100% (594/594), 1.35 MiB | 6.97 MiB/s, done.
Resolving deltas: 100% (163/163), done.
Submodule 'cmocka' (https://git.cryptomilk.org/projects/cmocka.git) registered for path 'cmocka'
Cloning into '/home/fgarcia/RetroPie-Setup/tmp/build/lr-caprice32/cmocka'...
remote: Enumerating objects: 144, done.        
remote: Counting objects: 100% (144/144), done.        
remote: Compressing objects: 100% (140/140), done.        
remote: Total 144 (delta 27), reused 8 (delta 1), pack-reused 0        
Receiving objects: 100% (144/144), 124.22 KiB | 201.00 KiB/s, done.
Resolving deltas: 100% (27/27), done.
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object f5e2cd77c88d9f792562888d2b70c5a396bfbf7a
Fetched in submodule path 'cmocka', but it did not contain f5e2cd77c88d9f792562888d2b70c5a396bfbf7a. Direct fetching of that commit failed.

**Comment by DSkywalk** [comment]
related: https://github.com/libretro/libretro-cap32/issues/116
