### ISSUE TITLE
Border  crop option issues 

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-cap32#138]
Hi,
The new border crop option is nice!
But 2 issues:
-when you toggle it, the change is not reflected, even after core restart. You have to close and open again.
-the virtual  keyboard is also cropped!

Cheers

**Comment by DSkywalk** [comment]
>  -when you toggle it, the change is not reflected, even after core restart. You have to close and open again.

At the moment, yup is a mandatory. And I prefer it that way, it's not something you're changing all the time, it was originally going to be a compile-time feature only.

>  -the virtual keyboard is also cropped!

In the similar way, the on-screen keyboard was going to be removed for this feature, but I preferred to leave it to be able to press some occasional key. We will have to redo the keyboard or make two versions, one trimmed and one full screen. The truth is that I prefer to simplify and have a new version a little more reduced.

These will be things to improve for next year, I hope you continue to enjoy the emulator! thx :)

**Comment by Vweber73** [comment]
Many thanks!
I fully understand. But please don't reduce the keyboard, it has to be usable on my Z fold 3, using all available width, even when the border is not cropped! :)
Cheers

**Comment by Vweber73** [comment]
Just one more thing: in border crop mode, not only the virtual keyboard is also cropped, but it is also completely unusable: the key presses don't match the right key, the mapping is totally wrong, as if the normal keyboard was still the base for the key presses...

Cheers

**Comment by DSkywalk** [comment]
I think was fixed some days ago, please update your core 👍

**Comment by Vweber73** [comment]
I have fd60b77, which I believe is the latest, yet I have this problem...

**Comment by Vweber73** [comment]
Many thanks! The mouse is correct now.
Too bad the first and last column of keys are unreachable. Hope this can be fixed, I love this border crop mode and would like to stick to it :)

**Comment by DSkywalk** [comment]
> *"don't reduce the keyboard"* and you also say *"last column of keys are unreachable"* 

I will try to find the best solution but something will have to be reduced, because there is no magic ;-)

Merry Christmast and enjoy! :christmas_tree: :sparkles:

**Comment by Vweber73** [comment]
Sorry I was unclear, when I said "don't reduce the keyboard" I meant "don't make it smaller in normal mode" and "please make it smaller (than currently) in border crop mode". I, short I meant that the keyboard should be the same and use 100% of the width, without being cut, whatever the mode is! 🙂

Man thanks for your kind wishes, merry Christmas to you too! 🙂
