### ISSUE TITLE
some games from cpc-clean-db 1.2 (from archive.org) are not working, but tosec versions from tosec package is ok

### ISSUE THREAD

**Issue by aderumier** [libretro/libretro-cap32#143]
Hi,

I have problem running some games from the cpc clean db 1.2 package
from:
https://archive.org/details/amstrad-cpc-clean-db

some games example:

sram2
qin
zombi (spain)
zombi (france)
zombi (de)

I have verified, the md5 of dsk are ok and match the .dat

but when I'm lauching them (libretrocap 4.5.4), I have a computer_hash_file error displayed and game is not launching.
Tested with caprice32, the game is not launching too.

If I used .dsk from tosec, the files have different size, and are working correcting (and no crc hash error in libretro)
https://archive.org/download/tosec-main/Amstrad/CPC/Games/%5BDSK%5D/Amstrad%20CPC%20-%20Games%20-%20%5BDSK%5D%20%28TOSEC-v2023-06-14%29.zip

**Comment by DSkywalk** [comment]
Verified CRC is that your rom is a clean certified version. Some **ORIGINAL** games from ERE have protections that cap32 cannot reproduce at this momment. All the games you mention are in fail-db (you see a notification when load this rom if you have that enabled). Check our list:
https://github.com/libretro/libretro-cap32/blob/master/libretro/db/db-fail.h

**Comment by DSkywalk** [comment]
The reason that exists **clean-cpc** is because tosec and other "rom packs" are plenty of cracked/bugged versions.

**Comment by aderumier** [comment]
thanks for your response !

Sorry, I was confused by clean-cpc-db_have.txt && clean-cpc-db_miss.txt,  I thinked that miss.txt was the non working games, and that the hash error was non matching hash.

Just curious, what is your tosec source with originals version ?

**Comment by DSkywalk** [comment]
As you can see in the issue, we started using tosec list as an started source and is was a totally mess... :wastebasket:

**Comment by aderumier** [comment]
@DSkywalk ah ok, I thinked you was only used tosec as source.

I have looked at another source of original disks,  in the  "amstradmaniav7" game compilation from 2014:

https://pixeldrain.com/u/HRKCge66

They are a "extras/original disk" directory  in the collection:

I tested some of them and they are all working:

sram
sram2
qin
bob morane - science fiction
skate ball
back to the future 2

**Comment by DSkywalk** [comment]
hello @aderumier!
 What is the source of this _original_ dump? because for example SRAM original disks are protected by 
`Protection Remi HERBULOT - 10-1985 - v2.1` (not working on cap32 yet)

more info: https://www.cpc-power.com/index.php?page=protection&lenom=Protection%20Remi%20HERBULOT%20-%2010-1985%20-%20v2.1

One more thing, could you correct your review in archive? because it can be misleading to other users, thanks! :+1:

**Comment by aderumier** [comment]
mmm, indeed I'm not sure they are the original.

I have tried to do myself convert with samdisk tool, from raw dump, and I got the same result, it's not working.

I see on cpc-power that the image is working with Sugarbox emulator, so maybe it's just no yet working with caprice32.

Thanks for your hard work !     (I'll try to contribute soon with remap)

(and I'll fix the comment on archive.org)
