### ISSUE TITLE
Multidisk (The Shadows of Sergoth)

### ISSUE THREAD

**Issue by Snapouille** [libretro/libretro-cap32#144]
Hi Sir,
I wanted to try shadow of sergoth again, but I ran into a new problem.
when you change floppy disks, the emulator performs a hard reset (not on all games), has anything changed in the code?

I've put together a very quick video to give you an idea:
[https://we.tl/t-fpGTWC5d5P](url)

Thanks in advance for your answer.

**Comment by DSkywalk** [comment]
Sorry, unavailable but working for me like a charm...

![imagen](https://github.com/libretro/libretro-cap32/assets/560310/7232ab1a-3b38-41d6-8424-eb2e26821358)
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/e2bad5ad-18ae-4839-ad5e-8ef56743888a)
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/aa699de7-796d-4017-849b-bbfaf5b9490a)
![imagen](https://github.com/libretro/libretro-cap32/assets/560310/7593c7db-7443-42ae-bcca-4a46d13b739c)
