### ISSUE TITLE
Amstrad GX4000 games not working

### ISSUE THREAD

**Issue by vahacris** [libretro/libretro-cap32#148]
Amstrad GX4000 games not working with newest version of cap32.

I try to run amstrad gx4000 games in cpr format (TOSEC set). I choose 6128+(experimental) option but games do not start - there is only standard basic screen (same as for amstrad cpc).

When i use older version of cap32 with 6128+ option (without experimental note) - i get basic v4 screen with menu where i can choose f1 - basic and f2 - burning rubber. after a while burning rubber starts and is playable, but how to run other amstrad gx4000 games?

**Comment by DSkywalk** [comment]
see: https://github.com/libretro/libretro-cap32?tab=readme-ov-file#known-bugs

CPC+ need 24bits of Color Depth

![imagen](https://github.com/user-attachments/assets/325a6107-a552-4f46-8f7a-7436176989ca)

**Comment by vahacris** [comment]
still can't load any game.

1. ramstrad gx4000 roms are from latest TOSEC
2. my core setup - screenshot no 1
3. the result - screenshot no 2
4. any  solution?
![ss1](https://github.com/user-attachments/assets/90038b1a-c41b-47fa-8782-77c8633875cb)
![ss2](https://github.com/user-attachments/assets/ee3fbf43-4795-42e9-ac24-e4a7a2477b6b)

**Comment by DSkywalk** [comment]
Please activate login and paste here, I am sure that you are missing something because run a CPR is really simple...

Lastest TOSEC _Amstrad GX4000 - Games - [CPR] (TOSEC-v2010-12-08_CM)/Barbarian II (1990)(Ocean).zip_
![imagen](https://github.com/user-attachments/assets/481d41fe-d2f7-4d8b-a356-9efa5856b861)

**Same core versión on Windows**

**Comment by vahacris** [comment]
Succed!
The problem was that i was running cpr file. When I try zip file it starts. 
Unzipped the file to cpr and You get the same error as me.
Zip file works perfectly but You need to zipped cpr file. The newest TOSEC packs contain unzipped files.

**Comment by DSkywalk** [comment]
Maybe you are trying to load a .BIN file? CPR works zipped and unzipped (zip only moves CPR to temp files and load from here).

**Comment by vahacris** [comment]
No, i use the same file. Just look at the video i recorded (link below as i cant add it as attachment).

https://drive.google.com/file/d/1GGwnDmvK1PKWwMc9jAPFaVZb25-TFLQA/view?usp=sharing

Other users got the same problem. I asked about this problem on various emulation forums (emumovies, launchbox) and discords and people use mame core to play amstrad gx4000 games in retroarch.

I will write the solution on launchbox forum as i'm active member there. it's strange that it worls for you and did not work for me and few others. 

As you can see there is a errorr message pointed that the rom is recognize as cpc rom. I could paste log file but i don't know how to genreate it, the logs folder i retroarch is empty.

**Comment by DSkywalk** [comment]
I am not the only one tested this think, for ALL my testers on windows are working as expected :+1: 

Can you move your rom to C:\test and try the same thing?

**Comment by DSkywalk** [comment]
> When i use older version of cap32 with 6128+ option (without experimental note) - i get basic v4 screen with menu where i can choose f1 - basic and f2 - burning rubber. after a while burning rubber starts and is playable, but how to run other amstrad gx4000 games?

Sorry but your assumption is totally wrong.

You are loading the PLUS BIOS because the old versions of cap32, if they didn't detect the CPR they loaded their default/internal BIOS (now it doesn't work like that for compatibility reasons). Therefore, it's not working on that old version either, as you say it doesn't load any other game... it simply doesn't load anything, neither that version, nor any other ;)

**Comment by vahacris** [comment]
ok, i moved retroarch to c:\ra and my rom to c:\rom and the problem is the same. maybe is just problem with my pc but it doesn't matter because i will just use zipped files. for me the problem is solved.

thanks a lot for the help, i really appreciate it, and keep up the good work.
