### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Marc34** [libretro/libretro-cap32#15]
Impossible to compll since the last changes. Ubuntu 16.04 64 bits.

cc -c -o libretro/core/libretro-core.o libretro/core/libretro-core.c -O3 -DLOG_PERFORMANCE -fPIC -D__LIBRETRO__  -DINLINE="inline" -DHAVE_CONFIG_H -Wall  -I. -I./cap32 -I./cap32/libcpccat -I./libretro -I./libretro/core -I./libretro/include -I./libretro/libretro-common/include
In file included from libretro/core/libretro-core.c:41:0:
libretro/core/cmdline.c: In function ‘Add_Option’:
libretro/core/cmdline.c:25:32: warning: embedded ‘\0’ in format [-Wformat-contains-nul]
    sprintf(XARGV[PARAMCOUNT++],"%s\0",option);
                                ^
libretro/core/libretro-core.c: In function ‘update_variables’:
libretro/core/libretro-core.c:154:7: warning: format not a string literal and no format arguments [-Wformat-security]
       snprintf(str, sizeof(str), var.value);
       ^
libretro/core/libretro-core.c:154:7: warning: format not a string literal and no format arguments [-Wformat-security]
libretro/core/libretro-core.c:185:7: warning: format not a string literal and no format arguments [-Wformat-security]
       snprintf(str, sizeof(str), var.value);
       ^
libretro/core/libretro-core.c:185:7: warning: format not a string literal and no format arguments [-Wformat-security]
libretro/core/libretro-core.c:191:5: warning: implicit declaration of function ‘change_model’ [-Wimplicit-function-declaration]
     change_model(val);
     ^
libretro/core/libretro-core.c:202:7: warning: format not a string literal and no format arguments [-Wformat-security]
       snprintf(str, sizeof(str), var.value);
       ^
libretro/core/libretro-core.c:202:7: warning: format not a string literal and no format arguments [-Wformat-security]
libretro/core/libretro-core.c:206:5: warning: implicit declaration of function ‘change_ram’ [-Wimplicit-function-declaration]
     change_ram(val);
     ^
libretro/core/libretro-core.c:235:7: warning: format not a string literal and no format arguments [-Wformat-security]
       snprintf(str, sizeof(str), var.value);
       ^
libretro/core/libretro-core.c:235:7: warning: format not a string literal and no format arguments [-Wformat-security]
libretro/core/libretro-core.c:250:29: warning: implicit declaration of function ‘video_set_palette’ [-Wimplicit-function-declaration]
              CPC.scr_tube=1;video_set_palette();}
                             ^
libretro/core/libretro-core.c:263:7: warning: format not a string literal and no format arguments [-Wformat-security]
       snprintf(str, sizeof(str), var.value);
       ^
libretro/core/libretro-core.c:263:7: warning: format not a string literal and no format arguments [-Wformat-security]
libretro/core/libretro-core.c: In function ‘retro_reset’:
libretro/core/libretro-core.c:371:2: warning: implicit declaration of function ‘emu_reset’ [-Wimplicit-function-declaration]
  emu_reset();
  ^
libretro/core/libretro-core.c: In function ‘retro_init’:
libretro/core/libretro-core.c:405:55: warning: embedded ‘\0’ in format [-Wformat-contains-nul]
    if(retro_system_directory==NULL)sprintf(RETRO_DIR, "%s\0",".");
                                                       ^
libretro/core/libretro-core.c:406:28: warning: embedded ‘\0’ in format [-Wformat-contains-nul]
    else sprintf(RETRO_DIR, "%s\0", retro_system_directory);
                            ^
libretro/core/libretro-core.c:408:41: warning: embedded ‘\0’ in format [-Wformat-contains-nul]
    sprintf(retro_system_data_directory, "%s/data\0",RETRO_DIR);
                                         ^
libretro/core/libretro-core.c: In function ‘retro_deinit’:
libretro/core/libretro-core.c:458:4: warning: implicit declaration of function ‘UnInitOSGLU’ [-Wimplicit-function-declaration]
    UnInitOSGLU(); 
    ^
libretro/core/libretro-core.c: In function ‘retro_audiocb’:
libretro/core/libretro-core.c:534:21: error: ‘x’ undeclared (first use in this function)
    if(pauseg==0)for(x=0;x<sndbufsize;x++)audio_cb(sound_buffer[x],sound_buffer[
                     ^
libretro/core/libretro-core.c:534:21: note: each undeclared identifier is reported only once for each function it appears in
libretro/core/libretro-core.c: In function ‘retro_run’:
libretro/core/libretro-core.c:568:7: warning: implicit declaration of function ‘retro_loop’ [-Wimplicit-function-declaration]
       retro_loop();
       ^
libretro/core/libretro-core.c:570:4: warning: implicit declaration of function ‘Retro_PollEvent’ [-Wimplicit-function-declaration]
    Retro_PollEvent();
    ^
libretro/core/libretro-core.c:572:9: warning: implicit declaration of function ‘enter_gui’ [-Wimplicit-function-declaration]
    else enter_gui();
         ^
libretro/core/libretro-core.c: In function ‘retro_load_game’:
libretro/core/libretro-core.c:629:4: warning: implicit declaration of function ‘tape_insert’ [-Wimplicit-function-declaration]
    tape_insert ((char *)full_path);
    ^
libretro/core/libretro-core.c:630:9: warning: implicit declaration of function ‘kbd_buf_feed’ [-Wimplicit-function-declaration]
         kbd_buf_feed("|tape\nrun\"\n^");
         ^
libretro/core/libretro-core.c:633:2: warning: implicit declaration of function ‘loadadsk’ [-Wimplicit-function-declaration]
  loadadsk((char *)full_path,0);
  ^
In file included from libretro/core/libretro-core.c:41:0:
libretro/core/cmdline.c: In function ‘pre_main’:
libretro/core/cmdline.c:65:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:294 : la recette pour la cible « libretro/core/libretro-core.o » a échouée
make: *** [libretro/core/libretro-core.o] Erreur 1

**Comment by r-type** [comment]
Previous commit delete declaration of x. Fixed now
