### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by Marc34** [libretro/libretro-cap32#16]
Keyboard is no more usable with controller only.

**Comment by r-type** [comment]
did you toggle (joypad select) to joypad mouse emulation ?

**Comment by Marc34** [comment]
I don't think so. Where do you see that ?

**Comment by r-type** [comment]
joypad select to toggle mouse/joypad in GUI .
or can you elaborate ,I m not sure to understand  the issue.

**Comment by Marc34** [comment]
ok, sometimes it is difficult to understand each others when we don't speak the same language... « Joypad select » : I was searching a menu for selecting the joypad. I understand now, and all work fine, thanks for your help and your work.

**Comment by fmarot** [comment]
Hello @Marc34 & @r-type . Sorry to bring back this issue from the dead but can you explain how to use the virtual keyboard please ? At least the one in latest Retropie (4.3) is unusable for me. I've written a post on Retropie forum: https://retropie.org.uk/forum/topic/13265/amstrad-cpc-and-keyboard
thanks !
