### ISSUE TITLE
Two players games

### ISSUE THREAD

**Issue by Tornelf** [libretro/libretro-cap32#17]
Hi. First of all i would like to thank you for your great job. I cried and cried playing gryzor again.  
I am using the amstrad emulator on reclabox 4.1. It is running retroarch with cap32 4.2. 
I would like to play two players games like gauntlet, ikari warriors and also barbarian (to have the pleasure to shorten some fiends as in the good old days). The issue is that second player doesn't seems to be implemented; In retroarch/settings/input menu, all the controls are set to N/A in player two input section. Is there a way to change this?

**Comment by r-type** [comment]
I push a commit to support joy1 , but untested , can you report here if it works for you?

**Comment by Tornelf** [comment]
I enabled joy1 and also tried to  tick jo1 and joy2 on the GUI (access via F10 key. It didn't work. I think i'm stuck with the N/A on player 2 binds as you can see on my screenshot.

![img_20170311_133922](https://cloud.githubusercontent.com/assets/26287698/23823452/553e89d6-0663-11e7-86ef-98c3ea977c85.jpg)

**Comment by r-type** [comment]
ok thanks for reporting i ll look at

**Comment by Tornelf** [comment]
OK, thanks !!!

**Comment by rockaddicted** [comment]
Hi, sine this commit https://github.com/libretro/libretro-cap32/commit/c762054974779343550803dd37304217e28e1a61, I can't control anymore with my gamepad.

**Comment by r-type** [comment]
Ok that is strange, as my ds3 not working anymore  i havn't tried a joy since this commit .
but now I experimented the same on the wiiu .
I'll look at  ! but can you confirm that it was working before this commit ? 
thanks for reporting.

**Comment by rockaddicted** [comment]
Hi, and thank you for your answer.
I built this commit this morning https://github.com/libretro/libretro-cap32/commit/04bffe89aa2aa0de94dedad7272d2e71f7dc724a and no problem to control player1 with a gamepad.

**Comment by r-type** [comment]
Thanks that will help . I'll look at and update here if something new.

**Comment by r-type** [comment]
I did a bas mistake ! 
can you try again  ?

**Comment by rockaddicted** [comment]
So, I tested a 1 player game (rick dangerous) and a 2 players game (gauntlet) and everything works well.
Thank you for this fix :wink:

**Comment by r-type** [comment]
thanks you for reporting !
at least there is at least one who use this core  :wink:

**Comment by rockaddicted** [comment]
It is the main amstrad cpc emulator on recalbox, so there is there is not only one person that is using this core.
Thank you for your good work.

This issue can be closed. @Tornelf I'm bumping the core version on recalbox.

**Comment by r-type** [comment]
ok then I close it
