### ISSUE TITLE
Trouble building on windows 10 64 bit.

### ISSUE THREAD

**Issue by NihilisticEevee** [libretro/libretro-cap32#18]
Hello I am trying to compile this under windows 10 64 bit with msys2 and i get an error. Anyideas on whats going on?
http://pastebin.com/s3RX0vs1

**Comment by r-type** [comment]
should #undef _C at the top of z80.h before line 62 that 
 #define _C

**Comment by r-type** [comment]
forgot, wasn't related , just unwanted define in libretro-core.c and include missing elsewhere.
that said , it need some fix for some strange nuklear behaviour (like was done in vice).
