### ISSUE TITLE
Image not filling up the screen

### ISSUE THREAD

**Issue by Voljega** [libretro/libretro-cap32#19]
Hello,

On Recalbox, the image isn't taking up the whole screen vertically, it is somehow a little bit reduced to a box in the center of the screen, smaller than what it should be (a 4/3 image taking up the whole screen vertically)

**Comment by WhitePatches** [comment]
Do you have Integer Scale turned on in Video settings?

**Comment by Voljega** [comment]
Yes, and turning of the Integer Scale resolve the issue. Thanks !
