### ISSUE TITLE
.bas, .bin, .aws and nothing - rom extensions

### ISSUE THREAD

**Issue by soydemadrid** [libretro/libretro-cap32#20]
Hi I just wondered about all the different file extensions and how to convert them for libretro-cap32.

My Amstrad collection has .bin, .bas, .aws and also images with no extension in there. None of these show up for me in Retropie with libretro-cap32 set as my Amstrad emulator.

Is there a way to get them to work or to convert them all to some other extension?

Thanks for any help.

**Comment by Enverex** [comment]
Apparently it needs .dsk or .cpc files.

**Comment by soydemadrid** [comment]
ah thanks ok. Is there a way to convert the ones I have over to .dsk / .cpc?

Thanks again!

**Comment by DSkywalk** [comment]
@soydemadrid maybe you are have the CPCGamesCD compilation?
You have a cpc compilation that have the game files "exported" from his original DSKs.
CPCGamesCD is not compatible with vanilla-caprice32/libretro-cap32.

----
¿Por que no usas los packs de archive o nvg?
Saludos!
