### ISSUE TITLE
no disk loaded

### ISSUE THREAD

**Issue by Kallin** [libretro/libretro-cap32#24]
I'm trying out this core for the first time, but it doesn't seem to show any disks loaded when it starts up. I'm not super familiar with amstrad cpc, but it seems like I should be able to run ```cat``` from what I've seen to see what discs are available, and it days it can't find a: drive.

I'm loading a file like:
Barbarian II (1990)(Ocean).cpr

via retro-arch. Any ideas what I might be missing?
Thanks!

**Comment by DSkywalk** [comment]
@Kallin, CPR is a cart. 

Carts are not supported ATM.
