### ISSUE TITLE
Build failed with emscripten

### ISSUE THREAD

**Issue by frthery** [libretro/libretro-cap32#25]
Hello,

There is a build failure with emscripten, i suppose below declarations should be added to app.c file: 
extern void kbd_buf_feed(char *s);
extern void retro_joy0(unsigned char joy0);
extern void retro_joy1(unsigned char joy1);
extern void retro_key_down(int key);
extern void retro_key_up(int key);

After build fix, emscripten core works perfect :
![emscripten-fruity](https://user-images.githubusercontent.com/7692842/35862741-fce46a5e-0b4c-11e8-97ab-081fbf986e93.png)

Regards

**Comment by DSkywalk** [comment]
Hello @frthery 

I start to check the GUI, I get a lot of warnings in this part and I think need a rewrite. 
Please test again in a few weeks.

thanks!
