### ISSUE TITLE
Drive A:  disc missing

### ISSUE THREAD

**Issue by zach-morris** [libretro/libretro-cap32#38]
Attempting to run a multi disk game from an m3u file:
3D Pool (1989)(Firebird Software).m3u

m3u file contains the following:
```
3D Pool (1989)(Firebird Software)(Disk 1 of 2).dsk
3D Pool (1989)(Firebird Software)(Disk 2 of 2).dsk
```

And those two files are located in the same directory as the m3u file.  Launching the m3u file results in the emulator not finding the disks.  Bringing up Retroarch options doesn't show any disk control options.
![image](https://i.imgur.com/6MXM8R6.png)

**Comment by DSkywalk** [comment]
tested again, works like a charm, thanks @zach-morris
