### ISSUE TITLE
Android crash when changing Core options Resolution

### ISSUE THREAD

**Issue by 2xtime** [libretro/libretro-cap32#48]
I found another crash i'm afraid. I changed the resolution in the quickmenu core options and now it always crashes when trying to run anything. Not sure how to change it back now ?

**Comment by DSkywalk** [comment]
@2xtime Android > Data > com.retroarch > files and remove retroarch-core-options.cfg

**Comment by 2xtime** [comment]
Thanks very much ! I was thinking those options were written to a ROOT required location and thought I was screwed !. I edited the file instead of deleting it as it looks like it contains options for all the cores.

Thanks again.

**Comment by SaucySarah** [comment]
Hi, not sure if it's because of this, but the emulator now crashes instantly when running any game ! I updated to https://github.com/libretro/libretro-cap32/commit/96157f6e212a40dff9a910849e039db78983257a

**Comment by DSkywalk** [comment]
@SaucySarah What is the last version that running ok in your android device?

thanks

**Comment by SaucySarah** [comment]
Unfortunately I haven't updated since March when you added the CPC+ updates. I'll see if I can get a log to tell me anything.

**Comment by SaucySarah** [comment]
Here's what I managed to catch when Retroarch crashes. I hope it means something useful !
[log.txt](https://github.com/libretro/libretro-cap32/files/3232805/log.txt)

**Comment by DSkywalk** [comment]
thanks @SaucySarah!

I dont no why, but now I need change optimizations to zero, to allow the core works even on commit https://github.com/libretro/libretro-cap32/commit/45707b8b8dea9ea6086b370fdb39c46675044643

I think we need some android developer to help me to debug this problem... is on copy surface, but the code with nuklear is a mess :(

I upload my temp fix in a while, thanks for your report :+1:

**Comment by SaucySarah** [comment]
It works again now without crashing, thanks ! (That buildbot takes a while !) Regarding Hires mode, i'm not sure of any games that use it. I tried a game called 'Forestland' which I think is hires but i'm not sure if it's displayed correctly.

**Comment by SaucySarah** [comment]
Also, I tried Burning Rubber CPC+ and it's very slow and stutters (it used to work almost perfectly). So I guess those Android optimisations really do make a difference.

**Comment by rsn8887** [comment]
Hello all. I had a crash on Android with recent commits on vice-libretro.

We fixed it by changing optimizations to -Ofast, see this commit:
https://github.com/libretro/vice-libretro/commit/5deed7a6648e96732d0c78bbf1c87a42b0ff4e16

Maybe -Ofast will help here, too, and make the emu running fast again on Android? Just a guess.

**Comment by DSkywalk** [comment]
I'm working on this, I start to remove nuklear-gui code and using new VRAM API direct access and is working great, but no GUI/KEYBOARD-ON-SCREEN at the moment...
