### ISSUE TITLE
CPC+ Green monitor emulation

### ISSUE THREAD

**Issue by DSkywalk** [libretro/libretro-cap32#49]
To achieve a correct green monitor emulation on **CPC+** we need a new function that converts **RGB colors to green-luma**. Ulrich give us this green values for _vanilla_ CPC, but the formula is unknown:

```
// original RGB color to GREEN LUMA converted by Ulrich Doewich
// unknown formula.
double colours_green[32] = {
   0.5647, 0.5647, 0.7529, 0.9412,
   0.1882, 0.3765, 0.4706, 0.6588,
   0.3765, 0.9412, 0.9098, 0.9725,
   0.3451, 0.4078, 0.6275, 0.6902,
   0.1882, 0.7529, 0.7216, 0.7843,
   0.1569, 0.2196, 0.4392, 0.5020,
   0.2824, 0.8471, 0.8157, 0.8784,
   0.2510, 0.3137, 0.5333, 0.5961
};
```

I worked hard [this weekend](https://twitter.com/dskywalk/status/1097073653425074177) to create this new function _video_palette_green_:
```
// Convert RGB color to GREEN LUMA
// check colours_green vs colours_rgb, we could use here a logarithm.
// https://en.wikipedia.org/wiki/Grayscale#Converting_color_to_grayscale
#define G_LUMA_R     0.2427
#define G_LUMA_G     0.6380
#define G_LUMA_B     0.1293
#define G_LUMA_BASE  0.071
#define G_LUMA_COEF  0.100
#define G_LUMA_PRIM  0.050

PIXEL_TYPE video_palette_green(double r, double g, double b) {
   double green_luma = ((G_LUMA_R * r) + (G_LUMA_G * g) + (G_LUMA_B * b));
   green_luma += (G_LUMA_BASE + G_LUMA_PRIM - (G_LUMA_COEF * green_luma));

   uint32_t green = (uint32_t) (green_luma * (CPC.scr_intensity / 10.0) * 255);

   if (green > 255)
      green = 255;

   return (PIXEL_TYPE) RGB2COLOR(0, green, 0);
}
```

The new function generates really close values: 
_(my_value == ulrich_value)_

```
0.5755 == 0.5647 0.5755 == 0.5647 0.7534 == 0.7529 0.9718 == 0.9412
0.1792 == 0.1882 0.3976 == 0.3765 0.4663 == 0.4706 0.6847 == 0.6588
0.3976 == 0.3765 0.9718 == 0.9412 0.9136 == 0.9098 1.0300 == 0.9725
0.3394 == 0.3451 0.4558 == 0.4078 0.6265 == 0.6275 0.7429 == 0.6902
0.1792 == 0.1882 0.7534 == 0.7529 0.6952 == 0.7216 0.8116 == 0.7843
0.1210 == 0.1569 0.2374 == 0.2196 0.4081 == 0.4392 0.5245 == 0.5020
0.2884 == 0.2824 0.8626 == 0.8471 0.8044 == 0.8157 0.9208 == 0.8784
0.2302 == 0.2510 0.3466 == 0.3137 0.5173 == 0.5333 0.6337 == 0.5961
```

Using original Ulritch values:
![imagen](https://user-images.githubusercontent.com/560310/52940489-fb75e880-3366-11e9-83ea-efb142959c0f.png)

Using generated values:
![imagen](https://user-images.githubusercontent.com/560310/52940516-12b4d600-3367-11e9-8450-73bd6b402503.png)

Ulritch:
![imagen](https://user-images.githubusercontent.com/560310/52940625-4263de00-3367-11e9-8b78-e48bb814c853.png)
Generated:
![imagen](https://user-images.githubusercontent.com/560310/52940591-3546ef00-3367-11e9-9555-9bc8f589ba78.png)
Color:
![imagen](https://user-images.githubusercontent.com/560310/52940643-4c85dc80-3367-11e9-9996-bbd5245d0609.png)

Color:
![imagen](https://user-images.githubusercontent.com/560310/52940881-e0f03f00-3367-11e9-8388-99c11fc269a6.png)
Ulritch:
![imagen](https://user-images.githubusercontent.com/560310/52940909-ec436a80-3367-11e9-9e83-ecc24f0a7c0f.png)
Generated:
![imagen](https://user-images.githubusercontent.com/560310/52940943-04b38500-3368-11e9-8ac8-c55675e76f62.png)

I think the results are very good, the image has greater contrast and the generated values are close to Ulritch.

If you do not agree with the current formula applied to green emulation. I created a gist to play with the formula and suggest new values:
https://gist.github.com/DSkywalk/14d92e3d37beee35d8c85e5d4fe3e37b
Calculate coefs/refs:
http://david.dantoine.org/ficheros/ra/color_modulator.7z

Thanks :+1:

**Comment by hizzlekizzle** [comment]
That looks really good IMO!

**Comment by zackizacki** [comment]
It does look better concerning brightness and contrast. But the general ratio 0%:100%:0% for RGB to green conversion does not seem to represent real phosphor screens. I have both screens, CPC464 green monitor and PC Monitor (with emulator) side by side and I always need to add about 15% blue, so that both screens match. You can see that all images of cpc464 screens you can goolge also have a little bluish note. What is your experience?

**Comment by DSkywalk** [comment]
I can do some tests by turning up the blue a little, no problem. I lost my green monitor many years ago, but I had it all my childhood. Thanks for your help @zackizacki :+1:

**Comment by DSkywalk** [comment]
# green phosphor screens test

## 0% (current)
![imagen](https://user-images.githubusercontent.com/560310/77247645-50072980-6c33-11ea-9263-dd303adf1238.png)

## 10%
![imagen](https://user-images.githubusercontent.com/560310/77247548-914b0980-6c32-11ea-8f3b-1427faa388e9.png)

## 15%
![imagen](https://user-images.githubusercontent.com/560310/77247558-ad4eab00-6c32-11ea-98bc-72e47f252077.png)

I think 15% is a little too much and we lose too much contrast.

I have compiled some binaries with different configurations (blue 5%, blue 10%, blue 15%) so you can try it out yourself, thx @zackizacki :)
http://david.dantoine.org/ficheros/ra/cap32_libretro-blue_tests.zip
