### ISSUE TITLE
3DS compilation fails

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-cap32#50]
http://p.0bl.net/93564

Let me know when the issues are fixed and I'll enable the core again on the buildbot.

**Comment by DSkywalk** [comment]
@twinaphex is affected by the same problem, nuklear (check issue #51)

**Comment by r-type** [comment]
same as for the wii, just deal with an #ifdef

**Comment by DSkywalk** [comment]
![imagen](https://user-images.githubusercontent.com/560310/53284224-8e40c980-3751-11e9-8f4f-fb5a4174371e.png)

My question: Is it necessary to have a filemanager/explorer to load a disk using the GUI?
Now that we have the new disk-control manager, people could use this or use load content as usually.

![imagen](https://user-images.githubusercontent.com/560310/53284232-9f89d600-3751-11e9-923f-a06f6511cb10.png)

That file loader also avoids all _launcher file-loader-code_ (*) and I think it isn't the job of a core and is not a good idea. Reinvent a wheel that we already have in the launcher.

Thanks! :+1:

**Comment by r-type** [comment]
I think its good idea to leave it in code, as i wrote the code and it is usefull for me and i use it.
Btw no cost for you to leave it as you dont have to maintin it. 

Also, evry time, they want to remove ingame gui in core,but if i had listen them, they will probably also remove the mame ingame osd:)

**Comment by DSkywalk** [comment]
Well take a look...
![imagen](https://user-images.githubusercontent.com/560310/53284909-93eedd00-375a-11e9-8201-3a0ac1af3858.png)
![imagen](https://user-images.githubusercontent.com/560310/53285112-3740f180-375d-11e9-97e7-cf12bb274d02.png)

The current code for the GUI is uncommented, it doesn't follow any consistent style or structure (what are those .i files?) and contains pieces without any functionality. 

I don't understand your reply, we collaborate in an opensource project. It's not a matter of removing anybody's code but to improve what we currently have and give it a functionality that can be used by everyone. Maybe for a quick port it's useful but for a long term solution I really think that this part of the code can be improved. 

I'm just trying to help.
