### ISSUE TITLE
Core does not support save states

### ISSUE THREAD

**Issue by ozy24** [libretro/libretro-cap32#52]
Hello,

I am running lr-caprice32 emulator within RetroArch but when I attempt to save or load a save state I receive the message "Core does not support save states".  Are there any plans to add this feature?  Many thanks.

**Comment by DSkywalk** [comment]
I'll take a look :+1:

**Comment by ozy24** [comment]
Thank you.  I forgot to add one detail:  I am running the emulator within RetroPie envirionment i'm not sure if there is the same issue within standalone RetroArch install..

**Comment by ozy24** [comment]
Many thanks for taking the time to implement this feature.. it works great!
