### ISSUE TITLE
CPC cpu speed parameter

### ISSUE THREAD

**Issue by smartin-wl** [libretro/libretro-cap32#58]
Hi!,

using standalone Caprice32 it's possible to customize the cpu clock speed, by specifiying the parameter "speed" on the cap32.cfg, but I don't see this option on the core options screen.

I tried using the parameter cap32_speed on retroarch_core_options file, but didn't work.
Would it be possible to have this parameter on the retroarch core?

Thanks!

**Comment by DSkywalk** [comment]
ATM, you cannot set the CPU SPEED. But /soon/ we can have it. :+1:

**Comment by smartin-wl** [comment]
Awesome, thanks!!

**Comment by DSkywalk** [comment]
ATM the core just support fixed speed, PSG generates some weird sounds if I change the CPU_SPEED variable. Sorry.

**Comment by DSkywalk** [comment]
I could try again in the future. but not now, sorry :(
Thanks for your report.
