### ISSUE TITLE
Typing pipe character from OSK

### ISSUE THREAD

**Issue by joolswills** [libretro/libretro-cap32#6]
Doesn't seem possible to type the pipe character from the OSK. appears on page 2, but when pressing outputs "6". if SHF is pressed it shows it to the right of SHF but that produces a backquote - Other keys also don't seem to output the expected characters - especially when SHF is pressed.

**Comment by hizzlekizzle** [comment]
yeah, there are a lot of characters that can't be typed from the OSK, unfortunately.

**Comment by r-type** [comment]
Should be fixed

**Comment by joolswills** [comment]
Thanks :)
