### ISSUE TITLE
Disk autorun fails when keyboard is remaped (.rmp)

### ISSUE THREAD

**Issue by nportillo2** [libretro/libretro-cap32#62]
Since new version disk autorun fails if a game has a mapped keyboard file (.rmp)

On screen you can see that autorun types som garbage characters like RUN"94102. instead of RUN"1942.BAS" so game fails to load.

Older versions works perfect. Very annoying since I mapped 200 games to play directly with a gamepad and now they are unusable.

Using emulationstation and retroarch combo windows and retropie.

**Comment by DSkywalk** [comment]
Please can you upload your rmp file and... 
what is your system locale?(language locale)

thanks

**Comment by nportillo2** [comment]
I'm using windows 10 with spanish language with i'm sure this problem has nothing to do with the OS since the same problem happens with retropie 4.4; on the raspberry everything works with the original downloaded retropie 4.4 image, but if you update the retroarch (and the cap32) the same error happens.

The system where autorun fails is 1.7.6 Cap32 4.5 6ca94b3
Using 1943 game as example, if I delete the 1943.rmp file and start the game without remapping file it autoloads the game succesfully with a _RUN"1943._ (but can not play since keys are not remapped to the gamepad). Once I'm in the game I can remap the keys.

But when I save the remapped keys from the menu (to 1943.rmp on config/remaps/cap32 folder) next time I try to autorun the disk autoload tries to run _ru2943_. and gets syntax error.

Not every game fails I would say 80%. It's easy to reproduce on almost every game.

I don't know how to upload any file here, but file "1943.rmp" is pretty clear and short, I copy and paste here:

input_player1_key_y = "121"
input_player1_key_x = "110"
input_libretro_device_p1 = "259"
input_player1_analog_dpad_mode = "1"
input_libretro_device_p2 = "259"
input_player2_analog_dpad_mode = "0"
input_libretro_device_p3 = "0"
input_player3_analog_dpad_mode = "0"
input_libretro_device_p4 = "1"
input_player4_analog_dpad_mode = "0"
input_libretro_device_p5 = "1"
input_player5_analog_dpad_mode = "0"
input_player1_key_start = "49"
input_player1_key_b = "304"


The system working without autoloading issues is retroarch 1.7.3 with cap32 4.2.

Thank you for your time!

**Comment by DSkywalk** [comment]
The problem is that keyboard_cb get false "release key" events, when amstrad_keyboard is selected on controls menu. Is a core problem, but i try to investigate. My last commit fixes the problem temporarily.

Code: https://github.com/libretro/libretro-cap32/blob/4e7a1a48b046a0a463a44d41fd584760381dcf58/libretro/retro_events.c#L394

**Comment by nportillo2** [comment]
Is there any way get a windows cap32_libretro.dll to test the fix?

**Comment by DSkywalk** [comment]
sure, just update your core using retroarch.

**Comment by nportillo2** [comment]
I can confirm it works, but now there is another issue, I open a new different ticket.
