### ISSUE TITLE
WiiU core support

### ISSUE THREAD

**Issue by ajcasanova** [libretro/libretro-cap32#69]
Hi David,
Is there any chance to compilate this AmstradCPC core for WiiU?. I'm still using your wiituka emulator on Wii, but would be great to have all the emulators together in one place, I mean, RetroArch WiiU with nice covers on screen. You are an experienced homebrew programmer for wii, that's why I'm asking you.
Thanks!. Saludos desde Málaga!!

**Comment by DSkywalk** [comment]
Sure, I'll take a look this chrismast hollidays! I guess I'll need HBL... anything more?
thanks @ajcasanova 
Saludos desde Graná!

Pd. #QAOP FTW! ;-)

**Comment by ajcasanova** [comment]
Hi David. Sorry, reading my post I think it would be a bit confusing. I was asking to compile a RetroArch core for RetroArch WiiU, not like a standalone emulator. For me, a strange surprise was discover that WiiU users of RetroArch hasn't access to any of two existing cores (Caprice32 or CrocoDS) of AmstradCPC as you can see in this small screenshot of current RetroArch 1.8.1 WiiU cores folder:

![image](https://user-images.githubusercontent.com/224876/69010003-0643c500-095b-11ea-8926-8699a435d347.png)

Thanks!!

**Comment by DSkywalk** [comment]
maybe WiiU need more work...

--
Hola antonio, quizá el emulador necesita más trabajo y por eso no se ha compilado. Durante las vacaciones de navidad puedo instalarme el HB channel y echarle un ojo a la versión para WiiU a ver que le falta :+1:
