### ISSUE TITLE
Still in development ?

### ISSUE THREAD

**Issue by Marc34** [libretro/libretro-cap32#7]
Very interesting port, but has a lot of bugs.

Some games don't start (Prince of Persia).

The keyboard is not very easy to use ; it does not fit always to the screen, and it hides the game so that it is difficult to know what to write.

Some enhancements could be great because CPC lacks of an easy to use emulator.

**Comment by r-type** [comment]
DSK version of prince of persia works for me
[Imgur](http://i.imgur.com/5WrbClY.png)
and yes OSK kbd is not very easy to use 

BTW , on my git i re-work a little on cap32 ,
for ex now  tape works if you can type a ```|tape``` and hit F10 to start load!

**Comment by Marc34** [comment]
I saw the last enhancements you have made. This is very good, thank you !
