### ISSUE TITLE
Multiple Tape

### ISSUE THREAD

**Issue by Solo187** [libretro/libretro-cap32#70]
The core works perfectly in every aspect, As far as i can tell. Just 1 issue im having though. I can find no way of swapping & inserting a tape that has multiple sides. Adding tape m3u support would easily fix the issue, As is the case with the vice x64 core. At the moment though with cap32 when trying an m3u with tapes the core assumes it is a disk & does not work

**Comment by DSkywalk** [comment]
This hollidays i'll take a look, thanks @Solo187 !

**Comment by DSkywalk** [comment]
I think it would be interesting to unify the code to make it valid for records and tapes. I'd like to investigate that :+1:

**Comment by DSkywalk** [comment]
The problem is that the library always waits for disks, it requires some work but we can make a multidevice-loading for the m3u.
