### ISSUE TITLE
Wireless keyboard issues

### ISSUE THREAD

**Issue by DAZZADOOBY** [libretro/libretro-cap32#71]
Using lr-caprice32 on retropie emulationstation. 

Another question for you, please.

I'm having issues with my wireless keyboards when trying to use the Amstrad CPC on the above. When I hit the S key, it types "sZ". When I hit x, it types "xX". I've tried changing my input type to Amstrad Keyboard but this didn't fix the issue. Any ideas? I've searched high and low on forums and Facebook groups without any joy. 

I'm a newbie to the scene so apologies if I've missed something obvious. 

Thanks in advance, 
Daz

**Comment by DSkywalk** [comment]
You need to activate focus mode:
https://twitter.com/libretro/status/1065748517539520512

Enjoy @DAZZADOOBY !

**Comment by DAZZADOOBY** [comment]
How do I get to this menu from emulationstation on my Raspberry Pi3?Many thanks,DarrenSent from my Samsung Galaxy smartphone.
-------- Original message --------From: David Skywalker <notifications@github.com> Date: 05/02/2020  19:30  (GMT+00:00) To: libretro/libretro-cap32 <libretro-cap32@noreply.github.com> Cc: DAZZADOOBY <darren.wilson99@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [libretro/libretro-cap32] Wireless keyboard issues (#71) You need to activate focus mode:
https://twitter.com/libretro/status/106748517539520512
Enjoy @DAZZADOOBY !

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libretro/libretro-cap32/issues/71?email_source=notifications\u0026email_token=AOMR43PGHLAO4R3UOOCTQ6LRBMHULA5CNFSM4KOS343KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK4VTEY#issuecomment-582572435",
"url": "https://github.com/libretro/libretro-cap32/issues/71?email_source=notifications\u0026email_token=AOMR43PGHLAO4R3UOOCTQ6LRBMHULA5CNFSM4KOS343KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK4VTEY#issuecomment-582572435",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DAZZADOOBY** [comment]
I've managed to change the game focus mode. It hasn't resolved my issue.Thanks,Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: David Skywalker <notifications@github.com> Date: 05/02/2020  19:30  (GMT+00:00) To: libretro/libretro-cap32 <libretro-cap32@noreply.github.com> Cc: DAZZADOOBY <darren.wilson99@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [libretro/libretro-cap32] Wireless keyboard issues (#71) You need to activate focus mode:
https://twitter.com/libretro/status/1065748517539520512
Enjoy @DAZZADOOBY !

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libretro/libretro-cap32/issues/71?email_source=notifications\u0026email_token=AOMR43PGHLAO4R3UOOCTQ6LRBMHULA5CNFSM4KOS343KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK4VTEY#issuecomment-582572435",
"url": "https://github.com/libretro/libretro-cap32/issues/71?email_source=notifications\u0026email_token=AOMR43PGHLAO4R3UOOCTQ6LRBMHULA5CNFSM4KOS343KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK4VTEY#issuecomment-582572435",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
