### ISSUE TITLE
Autorun fails when CPC language set to French

### ISSUE THREAD

**Issue by vbe75** [libretro/libretro-cap32#73]
Hi,

Retroarch version: 1.8.5
System: MacOS 10.14 (Macbook, AZERTY keyboard)

Retroarch fresh install, changing the CPC language option to French, autorun fails with the following message: "Syntax Error"

<img width="532" alt="Screen Shot 2020-04-05 at 18 18 25" src="https://user-images.githubusercontent.com/25487272/78511541-5fc25a00-776b-11ea-98b0-81afc20f06e7.png">

**Comment by DSkywalk** [comment]
I'll work on it this week, thank you very much for your bug report.

**Comment by DSkywalk** [comment]
I have been reviewing a solution the main problem is that the autorun has an old code that repeats the new implementation of the event system with multilanguage. I should try to optimize it and get that old code out of the emulator folder (which is not its place).
