### ISSUE TITLE
Disk activity indicator

### ISSUE THREAD

**Issue by vbe75** [libretro/libretro-cap32#74]
Please consider adding an optional disk activity indicator. It could be a blinking small square in the bottom right of the screen.

**Comment by DSkywalk** [comment]
This is something I would like to do, but before I add it a new GUI would have to be addressed. I'm adding it anyway because it's something just as important.

Thanks for your report @vbe75 !

**Comment by DSkywalk** [comment]
I suggest adding an option to show the disk activity indicator and the sound of the floppy disk drive by default, another option with only the indicator ( no sound #76 ) and finally only sound without disk indicator :+1:

**Comment by maksun** [comment]
Hello,

I'm answering here as the #76 is closed ;)
You're right as it would be perfect to have the choice to get sound only, led indicator only, both or none.
Something like "cap32_disk_activity = **led**|sound|both|none" for example.
Bold means led should be the default one.

Thank you for your prompt answer.

**Comment by evilforces** [comment]
Please consider removing the sound option when loading a floppy disk. 

Unlike other emulators, the disk loading sound is terribly loud and not very faithful to the sound of a floppy disk. 

It seems like they are bombing my house every time I load a disc, it is very annoying. I am using another emulator external to Retroarch just to avoid this problem.

A small visual indicator would be much better and less annoying. 

Thanks.

**Comment by DSkywalk** [comment]
Hello, this feature is already implemented in the new development branch.
![imagen](https://user-images.githubusercontent.com/560310/133051953-62e45147-5017-4a95-8298-c81dc70a4b8e.png)

I don't have much work to do before I can make it public for you all to test it.

**Comment by DSkywalk** [comment]
newui merged :wink:
