### ISSUE TITLE
Any option to disable disk noise? 

### ISSUE THREAD

**Issue by maksun** [libretro/libretro-cap32#76]
Hello,

I was wondering if there is any core option to disable the sound we can hear when .dsk is launched
for example?

I quickly checked in the code but found nothing.

Thank you.

**Comment by DSkywalk** [comment]
You talking about those wonderful floppy drive sounds that help you know a game is loading?

It wouldn't be hard to add an option like that, but I think we should at least have put an icon in first to help you check that the floppy drive is working. See #74

**Comment by DSkywalk** [comment]
Since they're related, I'm closing this one. Thank you very much for your report :smiley:
