### ISSUE TITLE
VKB is squeezed and RPi CPU hits 100%

### ISSUE THREAD

**Issue by crcerror** [libretro/libretro-cap32#83]
All is said in title.

1. Some cosmetic: The VKB is squeezed to the half screen per default and is not very readable then. Should be expanded to fullsize
2. More important: if the Keyboard is activated then htop shows 100% CPU usage on RPi3 and background music is choking. This will rise thermal thread of the CPU to 80°C and the Raspberry will show the small thermometer and the CPU will be slowed down. There should be a small timer added to lower VKB refresh/input.

Thanks

**Comment by DSkywalk** [comment]
The GUI needs to be revamped, but when I proposed it, it generated some controversy. And I don't feel like being bad about something that's a hobby.

**Comment by crcerror** [comment]
hmmm and about issue 2?

The VKB consumes CPU cycles and "weak" devices hit 100% CPU usage.
A sleep timer with 1000µs per frame should do the job easily,

**Comment by DSkywalk** [comment]
I see that vice64 finally removed nukleargui: https://github.com/libretro/vice-libretro/commit/d74caf5c7789ee0c8434be710e2f71af606543a2#diff-3827272601e2474f9625fd758a222e49

We'll do the same thing and use a similar approach. We're finally getting rid of that pain! :champagne:
