### ISSUE TITLE
remove Nuklear GUI, Add VKBD touch control

### ISSUE THREAD

**Issue by DSkywalk** [libretro/libretro-cap32#84]
We can finally get rid of the old Nuklear GUI. I'm going to try a similar approach to Vice64: 
https://github.com/libretro/vice-libretro/commit/d74caf5c7789ee0c8434be710e2f71af606543a2#diff-3827272601e2474f9625fd758a222e49

Removing nuklear should fix #28 #45 #48 #83

**Comment by DSkywalk** [comment]
new UI is almost ready :+1: 
https://twitter.com/dskywalk/status/1340381110556110848

**Comment by andymcca** [comment]
Hi @DSkywalk 
This looks sooooo much better than the old UI !!!  

But I notice it's not been committed yet - I built Cap32 for use on my LeapsterGS Explorer running Retroleap, and it still has the old Nuklear GUI.  This is basically unusable on the LeapsterGS as it has a fixed resolution of 320x240!  So can't even read the keys etc - 

Your UI looks like it will work so much better - do you have to use the mouse pointer to select keys or can you use the pad (i.e. arrow keys) like in Vice or Fuse?

Great job, hope you find time to commit soon

All the best
Andy

**Comment by DSkywalk** [comment]
> Hi @DSkywalk
> This looks sooooo much better than the old UI !!!

Thanks :tada: 

> Your UI looks like it will work so much better - do you have to use the mouse pointer to select keys or can you use the pad (i.e. arrow keys) like in Vice or Fuse?

Yep, you use the pad or keys, like vice :+1: 

I will try to make some progress today. And see what I need to finish, thanks for your comments!

**Comment by andymcca** [comment]
@DSkywalk great to see this being committed!!!  I think a lot of people look but don't comment on these kinds of changes so I wanted you to know that it is appreciated and I look forward to building / trying it out when I can (I'm working right now!)
