### ISSUE TITLE
Mingw cross compile broken

### ISSUE THREAD

**Issue by webgeek1234** [libretro/libretro-cap32#85]
This is a regression in the last 24 hours. I did a bisect and it indicated 29099ce. A log of the error is at:
https://gitlab.incom.co/libretro/libretro-cap32/-/jobs/39351

**Comment by bslenul** [comment]
Yeah, same for me and for the buildbot: http://paste.libretro.com/197145
And because of the recent RetroArch hack, the core isn't available at all for Windows anymore through the Core Updater menu :(
