### ISSUE TITLE
Gamepads don't work

### ISSUE THREAD

**Issue by extracampine** [libretro/libretro-cap32#87]
Gamepads don't seem to work with this core - whenever I press any button on my gamepad during a game, the screen kind of flashes and returns to the main screen or a select screen. I have tried setting the input method to Retropad, Amstrad joystick and Amstrad keyboard, and the issue persists. Any help appreciated!

**Comment by DSkywalk** [comment]
I can assure you that the controllers work fine :wink: 
There must be something wrong with the core or main control settings (which I doubt is the main one if the other emulators are working fine). Can you share the core control settings? Let me see if I can help you... :+1:

**Comment by extracampine** [comment]
Hi @DSkywalk , many thanks for helping out. Attached are 2 photos, one of the Quick menu/controls menu, and the other of the "Port 1 controls" menu within that. Any help appreciated!

**Comment by extracampine** [comment]
Any thoughts on this?

**Comment by DSkywalk** [comment]
The problem is clear that you have a problem in the configuration, try to ask in the retroarch discord group.
If you find any problems, you can reopen this report. Thank you very much and good luck!
