### ISSUE TITLE
(WiiU) New UI Keyboard not showing correctly 

### ISSUE THREAD

**Issue by Ploggy** [libretro/libretro-cap32#89]
I saw the NewUI changes and though I'd give it a try on the WiiU cap32 Core but the Keyboard overlay isnt displaying correctly?
![cap32-161006-075424](https://user-images.githubusercontent.com/1160255/133347183-d3cd850d-6c8b-4e24-b1f2-07638bc9892c.png)
(excuse the awful squashed pic) :P

**Comment by DSkywalk** [comment]
I have pushed a test that should fix the problem, please confirm that it works :+1:

**Comment by Ploggy** [comment]
Hi, I've compiled and tried your new version.. The keyboard now shows the correct graphic but has a red tone...

![cap32-161210-012318](https://user-images.githubusercontent.com/1160255/142461090-a8890068-3716-4134-92fe-55e87b7a389a.png)

**Comment by DSkywalk** [comment]
f*ck! :astonished: 
Ok, i need a WiiU for test :cry:

**Comment by DSkywalk** [comment]
@Ploggy What do you use to run the core? Can I use cemu for testing?

**Comment by Ploggy** [comment]
I use a WiiU :P I'm not sure if it's possible to run Retroarch on Cemu? I haven't got a PC fast enough to run Cemu on :/

**Comment by DSkywalk** [comment]
I pushed a new brach to test with your help :)
Could you compile the WiiU branch?

 https://github.com/libretro/libretro-cap32/tree/wiiu-test
 
 Thanks!

**Comment by Ploggy** [comment]
Sorry for late reply was asleep when you posted that msg :)

Good News, your test branch build works perfectly!!

[cap32-161210-190633](https://user-images.githubusercontent.com/1160255/142609396-aecdb57c-2ae4-4ace-b8f1-9e2e3b15dce4.png)

Thank You so much!!

.
