### ISSUE TITLE
no more access to the gui

### ISSUE THREAD

**Issue by rockaddicted** [libretro/libretro-cap32#9]
Hi @r-type 
Since this commit 9110a719dd5c2482fd14ffec70ad35e65e8342d7 I can no more access to the GUI or the OSK using my gamepad. So is it normal, WIP ? Or I'm missing something ?

**Comment by r-type** [comment]
In keyboard mode you have to use F8/9/10 to access GUI .
in joy mode to use virtual kbd to select GUI in page2.
it's not bind yet to a joystick button.

you may also need to change retro controller port setting to
Amstrad Joystick or Amstrad Keyboard .

**Comment by rockaddicted** [comment]
Thanks for your answer, it is ok.
I looked only in core options... I love the auto-boot feature, great job.
