### ISSUE TITLE
Remove Borders on Screen Display?

### ISSUE THREAD

**Issue by andymcca** [libretro/libretro-cap32#91]
Is it possible to remove the screen border, in the same way I can do on Fuse and Vice?

I've checked the core options but I don't think it's currently possible to do it.

**Comment by DSkywalk** [comment]
You have the RA video options to customize your screen, anyway I'll have a look to see what it's about (fuse/vice). Think that there are games like arkanoid that do overscan effects that wouldn't be compatible with something like this, the CPC is a complex machine with a custom gatearray used for screen effects, scrolls...

Thanks for your report! :+1:

**Comment by andymcca** [comment]
@DSkywalk - looking at his repo, in here - https://github.com/KaosOverride/CapriceRPI/tree/master/src/videodraw.  Looks like SDL_rotozoom is doing the work to remove the borders

**Comment by DSkywalk** [comment]
I have reviewed the code and using SDL_rotozoom seems to me a horrible idea... If it's already difficult to get the emulation to work properly on small devices, adding more layers to fake the emulation will make it even worse.

Sorry, I prefer to stay close to the original computer. Thanks for your feedback anyway :+1:
