### ISSUE TITLE
Android: mode 2 screwed up and keyboard issues

### ISSUE THREAD

**Issue by Vweber73** [libretro/libretro-cap32#92]
Hi,

Congrats for this very solid core !

Two problems on Android:
-Mode 2 characters are screwed up, as it some yellow painting had been applied in some places...
-The new on screen Amstrad keyboard is nice and realistic, but next to unusable with a mouse pointer. Could the keys made directly touchable, like for the Amiga P-UAE core ? Also, the keyboard has not transparency, so it masks the screen... It would be nice to have it off the screen limit, or, if Retroarch does not allow this, at least to have some tunable transparency, again like for the Amiga.

Many thanks and best regards

**Comment by Vweber73** [comment]
Many thanks for your reply ! I really would love to have a working mode 2 (it looks ok on small screens but is corrupted on big ones) - maybe this is just a very small bug to fix ? and a usable touch keyboard, to be able to use Basic, CP/M, and handle games easier :)
Many thanks for taking this into consideration !
Best regards

**Comment by Vweber73** [comment]
Here is my Samsung Z Fold3 trying to display TRIDI introductory question.
You can see that it is as if yellow painting had been spread on the text...

Many thanks and cheers,

Vincent

Le sam. 16 oct. 2021 à 12:58, David Skywalker ***@***.***> a
écrit :

**Comment by Vweber73** [comment]
LO.
How to change it to HI ?
The CrocoDS core on the same phone has no problem with mode 2 (although it
has many other problems that makes it way less usable than Caprice32).

Cheers

Le sam. 16 oct. 2021 à 13:14, David Skywalker ***@***.***> a
écrit :

**Comment by Vweber73** [comment]
Excellent, many thanks ! Any idea of when the new core will be available on
Google play store ?

Best regards

Le sam. 16 oct. 2021 à 13:21, David Skywalker ***@***.***> a
écrit :

**Comment by Vweber73** [comment]
I managed to get the new version through the non-store version of
Retroarch. Mode 2 works like a charm now, many thanks ! :)

Now if only the keyboard could be usable as the Commodore cores (touch
screen keys instead of mouse pointer, configurable transparency, and not
hiding the screen) I would be a very happy man !

Cheers,

Vincent

**Comment by Vweber73** [comment]
Hi,
I'm desperate to get a usable keyboard on the CPC... ;) Any roadmap for that would be deeply appreciated !
Many thanks and best regards

**Comment by DSkywalk** [comment]
My spare time unfortunately has no roadmap. I have pushed a change I was testing which should solve the problem :+1:

**Comment by Vweber73** [comment]
Hi,

Many, many thanks for doing this and sparing the time - this is deeply
appreciated !

This is much better than before - now, you can type a small command with no
issue. However, it is not perfect:
1) It is very hard to get a key to go into auto-repeat mode. You have to
tap several times. It seems that this is due to the fact that the tapping
relies on moving the mouse pointer to the right key, rather than testing
the key itself ? Flight simulator games such as Fighter Pilot require
auto-repeat (Q to increase the engine power, for instance);
2) It is quite slow responding. You can't type very fast, probably due to
the mouse as well; in fact this mouse pointer is quite enjoying, I would
love to get rid of it...
3) there is no visual feedback when you press a key;
4) The keyboard has no tunable transparency. This would be very good to
continue to see the screen when the keyboard is on. Like the Commodore
machines (64, 128, Amiga).

Do you think anything could be done for these issues ?

Many thanksnagain, and best regards,

Vincent

Le jeu. 18 nov. 2021 à 15:43, David Skywalker ***@***.***> a
écrit :

**Comment by DSkywalk** [comment]
Sure! :+1:

**Comment by Vweber73** [comment]
I will, promise ! :)
Many thanks and cheers

Le jeu. 18 nov. 2021 à 19:59, David Skywalker ***@***.***> a
écrit :

**Comment by DSkywalk** [comment]
Hello, now that I have more time, I would like to comment on a few things. 

- Regarding problem **1)** that you mention, it is how the CPC works, when you press a key it takes a few seconds until it repeats, that is something that is not going to change. 

- For problem **2)** you could remove the cursor in android or make it optional, but I wouldn't want to fill everything with crazy options. 
- In problem **3)** is something that I have in mind to improve and **4)** is something that could not be general to all devices, making the blending by software is very slow... I have to think about it :coffee: 

I'm going to create a new report, with these details, if you see something else I'll try to add it. Thanks! :+1:

**Comment by Vweber73** [comment]
Hi,

Many thanks for your quick answer.

For #1, I know the CPC takes a little while to auto-repeat, but that's not
what I mean. I mean that you have to tap several times, and then hold, for
auto-repeat to occur. Just holding and waiting will not do it, most of the
times. Caprice32 for DOS or Windows does not have this problem at all !

For #2, I understand about the mouse pointer, but still, it is too slow to
respond. It is impossible to type fast on the keyboard, while it is very
possible in DOS or Windows versions, or on Commodore cores within Retroarch.

For #3, noted with thanks.

For #4, look at Commodore cores. They handle transparency to perfection :)

Thanks a lot and cheers,

Vincent

Le ven. 19 nov. 2021 à 13:02, David Skywalker ***@***.***> a
écrit :

**Comment by DSkywalk** [comment]
I have added a change that should improve the TAP detection. Let me know if you notice the improvement :+1:

**Comment by Vweber73** [comment]
Hi, many thanks for your very quick answer !

I updated the core to version ae6c307 HI.

I notice a very slight improvement on tap detection, but:
- Auto-repeat still does not accur when you just tap and hold, only when
you tap-tap-tap and hold;
-Still the same lag between the time you tap a key and the time it is
actually detected, no way to tap a text normally...

Cheers,

Vincent

Le ven. 19 nov. 2021 à 14:14, David Skywalker ***@***.***> a
écrit :

**Comment by DSkywalk** [comment]
The change was added on 22a0d37

**Comment by Vweber73** [comment]
Ah ok, sorry.

Still not available for me in the online updater. Will check regularly and
revert.

Cheers

Le ven. 19 nov. 2021 à 14:24, David Skywalker ***@***.***> a
écrit :

**Comment by Vweber73** [comment]
I could test it. Many, many thanks and congrats !! Save for the useless and
ennoying mouse pointer, tapping and auto-repeat are now the way they should
be, perfect !!

If only the keyboard was not hiding the screen. Either transparency, of
having a way to move it outside the screen space, it would be truly usable
:)

One possible improvement would be an option to hide the numeric keypad - so
that the other keys are larger and easier to tap.

And of course the visual and haptic feedback :)

Something else - any plan to support the rom cartridges (.rom files) ?

Thanks again for this superb job and regards,

Vincent

**Comment by DSkywalk** [comment]
Hello again!

Think that the purpose of the on-screen keyboard is not to replace the control that you can set up on a controller to press certain keys (check the retroarch doc to configure it :+1: ), it is only to press a specific key at specific times. I have the impression that you want to play a game with the on-screen keyboard and I think it's completely insane :wink: 

I don't know if you mean the CPC PLUS cartridge games, these are supported since a while ago, it was my first contribution in retroarch, but the files have .CPR extension. (google: "TOSEC_V2017-04-23")
![imagen](https://user-images.githubusercontent.com/560310/142672999-3f10ea79-94df-40ab-b573-734145daca0a.png)

Thank you for your comments and suggestions and I hope you enjoy it.

**Comment by Vweber73** [comment]
Hi again,

Well, having the keyboard on screen is not insane for:
-Flight simulators, such as Fighter Pilot, relying on a large numbers of
keys for control;
-Basic programming (yes, I enjoy that !);
-CP/M, like using Turbo Pascal.

I owned a 464 then a 6128 37 years ago, and I love to re-live the feelings
I had with it, on my (large) phone - Samsung Z fold 3. Call me insane - I
am, but aren't we all insane to play with 40-year old computers !  :)

I was more talking about utility cartridges - Protext word processor, etc...

Thanks again and cheers,

Vincent

Le ven. 19 nov. 2021 à 19:26, David Skywalker ***@***.***> a
écrit :

**Comment by DSkywalk** [comment]
Well, the truth is that then we are both a bit crazy, I use a keyboard like this on android.
![imagen](https://user-images.githubusercontent.com/560310/142722485-3121d22d-dbc9-4ad4-ad5c-e21fb114e17d.png)

Some time ago I asked for a surface to draw interfaces and for retroarch to make it available to paint the keyboard, make transformations, etc... but that is still a long way off, that's why I bought it :money_with_wings: 
I really enjoy doing little IF in basic :smiley: 

I think it would be a good addition to the emulator to allow ROM loading, although I don't know if it's something we could do in retroarch, do you know of any example of a core that allows loading custom BIOS?I can take a look at it.
If you want, create a report and I'll investigate it :+1: 

thanks!

**Comment by Vweber73** [comment]
Hi,

Great keyboard ! Is it possible to use it with your Cpc core ?

But I still prefer on-screen virtual keyboards - everything in the pocket.
That's the main reproach I have for Retroarch on Android: most computer
emulation cores, when they have a keyboard, put it on the computer screen.
The real estate is not optimized, the cores don't own all the surface of
the phone, a lot of which is wasted with retroarch gaming controls. I
really would like this to be more configurable.

The best computer emulator on Android, to me, is Hataroid (Atari ST
emulator). Take a look at it, the développer understood everything about
mobile UI. You have a nice virtual keyboard, you can move it, zoom it, to
get exactly what you want. I wish there was a CPC Android emulator like
that. DroidCPC and CPCEmu don't bother to provide a keyboard. At least you
do ! :) With transparency it will be usable, even if my preferred option
would be to move the keyboard outisde of the CPC Screen, like Hataroid.

The best option I found is to use *two* emulators in a row: first, Ldosbox
for DOS emulation, this one provides a nice virtual PC keyboard that is
suitable for the CPC. Then, Caprice32 of No¢cpc for DOS. The phone is
powerful enough for this chain to work smoothly, but it is not as reliable
as a native emulator, and Caprice32 for DOS is an old version, the Batman
forever demo for instance, that pushes the CPC to its limits, does not work
on it... Yours is much more modern and works flawlessly, if not for the
keyboard masking the CPC Screen ;)

Regarding rom cartridges, no rush really, I have much less need for that,
it was just to be exhaustive. I prefer, if you have limited spare time,
that you spend it on the keyboard issues :) if you want examples, le Vice
C64 core on retroarch (cycle-exact version) does an outstanding job in
handling such peripherals...

Thanks again and cheers,

Vincent

Le sam. 20 nov. 2021 à 11:15, David Skywalker ***@***.***> a
écrit :
