### ISSUE TITLE
[WiiU] Games Fail to Autoboot

### ISSUE THREAD

**Issue by Ploggy** [libretro/libretro-cap32#95]
When ever I try to load a Game it fails to autoload, it writes some of the commands but doesn't complete..
This happens when attempting to load Daley Thompson's Decathlon.. Classic ;)

![Daley Thompson's Decathlon (UK) (1985)-161210-201431](https://user-images.githubusercontent.com/1160255/142618977-4b954980-7bd0-478e-b6a5-1e3dd1e50144.png)

**Comment by DSkywalk** [comment]
I will try to debug what happens to you by putting a text in the CPC and you can send me a screenshot of the result, ok?
This will take time and could be unstable, keep your caprice32 stable cores safe. These will be simple tests to give me clues. 

On linux this is the result:
![imagen](https://user-images.githubusercontent.com/560310/142627809-cf7cd3ea-325c-442b-b74a-c931ca1fb735.png)

Thank you very much! :+1:

**Comment by Ploggy** [comment]
This is the result....
![Daley Thompson's Decathlon (UK) (1985)-161210-215913](https://user-images.githubusercontent.com/1160255/142630911-5126b387-1953-41de-8171-a7083212d2a1.png)

**Comment by DSkywalk** [comment]
new test! :+1:

**Comment by Ploggy** [comment]
The pic is the same as the last.
![Daley Thompson's Decathlon (UK) (1985)](https://user-images.githubusercontent.com/1160255/142662931-82ef8120-86ca-4e38-8334-19be84016acd.png)

**Comment by DSkywalk** [comment]
No possible, you must have done something wrong because you should have at least added a space between DBG :no_good:

**Comment by Ploggy** [comment]
apologies yep, I messed up..
This is the pic.

![Daley Thompson's Decathlon (UK) (1985)-161211-014655](https://user-images.githubusercontent.com/1160255/142664505-5191b58c-3ec6-4fef-a7af-b598b4772352.png)

**Comment by DSkywalk** [comment]
test3!

![imagen](https://user-images.githubusercontent.com/560310/142666688-59226657-b020-4dfc-8b0f-765ec1c8de1c.png)

**Comment by Ploggy** [comment]
A bit of progress made I think? something different anyway :)
![Daley Thompson's Decathlon (UK) (1985)-161211-022051](https://user-images.githubusercontent.com/1160255/142668908-ed5608ee-91d7-4b4b-ba9d-ab70bcae10d1.png)

**Comment by DSkywalk** [comment]
test4!
![imagen](https://user-images.githubusercontent.com/560310/142671180-9b2c068e-7f43-445e-9eef-0dbf26e8cb15.png)

**Comment by Ploggy** [comment]
Little bit more info again this time :)
![Daley Thompson's Decathlon (UK) (1985)-161211-025330](https://user-images.githubusercontent.com/1160255/142672914-694ffd10-9cfb-48da-b785-4c7f422f35f7.png)

**Comment by DSkywalk** [comment]
test5 & my last hope!
![imagen](https://user-images.githubusercontent.com/560310/142674807-009ed333-92cb-4e28-bf9e-80350035488a.png)

**Comment by Ploggy** [comment]
What is it your looking for? the WiiU to be the same as your pic?

**Comment by Ploggy** [comment]
Here is the next one :)
![Daley Thompson's Decathlon (UK) (1985)-161211-034015](https://user-images.githubusercontent.com/1160255/142678450-a9dec6d9-6889-4df1-b029-bfa79c152307.png)

**Comment by DSkywalk** [comment]
Your image is not from the lastest code. Please check your source again! :)

**Comment by Ploggy** [comment]
100% is correct, I did it all from scratch to be sure....
![Daley Thompson's Decathlon (UK) (1985)-161211-042340](https://user-images.githubusercontent.com/1160255/142683794-462400a4-f0e6-478c-a123-0171cd262adc.png)

**Comment by DSkywalk** [comment]
You arre right, new code pushed!

**Comment by Ploggy** [comment]
Something new :D hopefully useful...
![Daley Thompson's Decathlon (UK) (1985)-161211-045005](https://user-images.githubusercontent.com/1160255/142686921-40bb3c6a-3530-4059-8107-52f552da4e6f.png)

**Comment by Ploggy** [comment]
oops, only now seeing that 😕 emoji :P 
Things aren't looking good?

**Comment by DSkywalk** [comment]
So basically it's all wrong :sob: 
The library that reads the archive in DSK is not big-endian compatible :red_circle:

**Comment by Ploggy** [comment]
Oh :/ well ok then lol there's not much that can be done about that, WiiU does have a CrocoDS Core so all is not lost :) Touchscreen doesn't work tho and the on screen keyboard isn't as snazzy looking as yours, but its a way to get Amstrad on WiiU :D 

Thank You for taking the time and looking at the issue.

**Comment by DSkywalk** [comment]
Wait, I haven't given up yet.

https://user-images.githubusercontent.com/560310/142730945-ff3e5d98-1c2c-4fd4-beca-898b01343638.mp4



https://thumbs.gfycat.com/MedicalGrandioseIguanodon-mobile.mp4

**Comment by Ploggy** [comment]
HAHAHA.  That's good to hear/see lol .. If you keep chipping away at the issue.. I'll keep testing whatever you put out ;) 
Thanks :)

**Comment by DSkywalk** [comment]
revised all fdc/slot and created new loader endian-compatible :+1: 

first test :smile: 
![image](https://user-images.githubusercontent.com/560310/142764042-1576e9ff-55da-42ef-b8fc-efa210ee8742.png)

**Comment by Ploggy** [comment]
Here you go.. looks good!
![Daley Thompson's Decathlon (UK) (1985)-161212-224408](https://user-images.githubusercontent.com/1160255/142765377-c250cdd8-1206-49b9-b80b-a682f3525f63.png)

**Comment by DSkywalk** [comment]
Yeah!!

**Comment by DSkywalk** [comment]
Please test the new code :+1:

**Comment by Ploggy** [comment]
Working!!! way to go Rambo!!!! :)
![20211122_220943](https://user-images.githubusercontent.com/1160255/142942701-02a4c872-267c-4cf6-a185-a7ae2968d77f.jpg)

**Comment by DSkywalk** [comment]
Perfect!!

I have rewritten a new code that I used in my old emulators (http://david.dantoine.org/proyecto/4/) and I have taken advantage of all the information that the emulator already has by default. I still need more work on SYSTEM disks and clean them up, but if this already works for you, you won't have any more issues.

enjoy and thanks!

**Comment by Ploggy** [comment]
Thank You VERY much!!

**Comment by DSkywalk** [comment]
Hello again @Ploggy! 

uploaded final code, please test with DC and:

* http://david.dantoine.org/ficheros/ra/ArmyMoves.zip
* http://david.dantoine.org/ficheros/ra/boulder1.zip
* http://david.dantoine.org/ficheros/ra/abadia.zip

Thanks!!

**Comment by Ploggy** [comment]
Hi there, 
All 4 of those games booted and ran fine! 
Everything looks good.

Thanks again for your help. It's been fun testing out your builds :)
