### ISSUE TITLE
[KoS] enhancements

### ISSUE THREAD

**Issue by DSkywalk** [libretro/libretro-cap32#96]
### IMPROVEMENTS

- [ ] key press visual feedback (haptic response?)
- [ ] apply blending-blit to the keyboard software driver

### ...
- :interrobang:  an option to hide the numeric keypad (The problem is that it would change the size of all the assets, so I almost discard this, it would be having two keyboards with two UI...).
- :pray: The desirable thing would be to have a surface to draw on provided by retroarch, with transformations for zooming in/out, etc... At the moment this is not available for the cores.

**Comment by Vweber73** [comment]
Hi,
I noticed there is a new core version, but could not find anything changed. Any hidden options ?
Many thanks and best regards

**Comment by Vweber73** [comment]
Hi,
Any progress on this one ? :)
Many thanks and best regards

**Comment by Vweber73** [comment]
Hi,

You've forgotten me... ;)

Many thanks and best regards
