### ISSUE TITLE
[WiiU] The WiiU Gamepad's Touchscreen "TAP" Doesn't Respond 

### ISSUE THREAD

**Issue by Ploggy** [libretro/libretro-cap32#97]
With the Cap32 Core its possible to use the the WiiU Gamepads Touchscreen as a Mouse Pointer, which works fine. but when I try to Tap to select a key on the On-screen Keyboard the Tap isn't registered.
I can manually set the Touchscreen Tap to the "A" Button in the Input settings and this works fine, but then the A button stops working lol
This is why I said it was minor, would it be possible to have the Touchscreen Tap AND the A Button mapped the same time?
The Tap works fine in the Vice Core on WiiU if you need a reference :)

**Comment by DSkywalk** [comment]
Please test the lastest commit :+1:

**Comment by Ploggy** [comment]
Fix works perfectly! 
Thank You
