### ISSUE TITLE
The core does not work, constant noise and extremely slow

### ISSUE THREAD

**Issue by ToniBC** [libretro/libretro-cap32#99]
Hello, this core stopped working, I hear a constant noise when starting it up and it works very slow, even if you load it without game.

This did not happen before and it worked without problems. It seems that it was something of the last updates.

All tested under Retroarch Nightly and updated cores (as of this post) under Windows 10 x64.

Thank you.

**Comment by Adancete23** [comment]
Yes, same problem here.

Was working perfect some updates before, but now a strong noise in every game, and running so slow.

Thanks in advance and happy christmas!.

**Comment by DSkywalk** [comment]
Which was the release that worked correctly for you guys?

The last changes were the autorun, which doesn't affect rendering and the change for the pointer on android/wiiu, which shouldn't affect rendering either :?

I don't use windows 10, so I can't test it. But it's very rare that it happens to two users at the same time. can you upload your retroarch configuration? can you post the RA startup log with verbose?

Thanks and happy holidays!

**Comment by ToniBC** [comment]
Apparently the error is related to the latest versions of Retroarch, I would have to look to see from what version happened, but with the latest nightly that core does not work. I think it only affects Caprice's core. With the 1.9.14 stable it does work, but it would be a problem with the 1.9.15 release.

**Comment by DSkywalk** [comment]
ping @twinaphex ! :sos:

**Comment by ToniBC** [comment]
The oldest version of Retroarch.exe is the one from the 20th, that one continues to fail, if you put the .exe of that Version or later, the core stops working.

The latest versions would have to be reviewed, it could be a problem with the new options format or something like that or with the netplay.

I enclose the logs, of the last nightly and the stable.

[retroarch (1.9.14 stable).log](https://github.com/libretro/libretro-cap32/files/7799552/retroarch.1.9.14.stable.log)
[retroarch (last nightly).log](https://github.com/libretro/libretro-cap32/files/7799554/retroarch.last.nightly.log)

Thank you.

**Comment by veganvelociraptor** [comment]
Same error occurs with a freshly cloned and compiled git snapshot of Retroarch.

I've no idea what has changed or why it only affects this core.

**Comment by ToniBC** [comment]
Interesting and curious that it also happens with the Jaguar. Let's see if they find out what it is, because with the release of the new version that will soon be released, many more will say so.

**Comment by veganvelociraptor** [comment]
I've checked the different commits for Retroarch, since this issue started after the Christmas holidays.

Just like someone else suggested, the majority of changes are in the netplay code. And I don't see how this should affect cores when not using netplay. Nevertheless, it must be a new bug of some kind in Retroarch. I'll see if I can spare time to dissect the commits, and I'll report the bug to the Retroarch repo if I find the cause.

**Comment by DSkywalk** [comment]
really thanks for your dissect, i'll try to reproduce on linux :+1:
